### ISSUE TITLE
Staff Moderation Frontend

### ISSUE THREAD

**Issue by sdaugherty** [modrinth/knossos#1]
Before authors can submit mods/modpacks directly to modrinth, there needs to be a robust moderation interface which will allow staff to support and moderate authors (and commenters).

Some of the things that this needs to account for:

- [ ] IP banning
- [ ] account banning
- [ ] account / ip histories
- [x] approval queues
- [ ] spam blacklist
- [x] DMCA removal
- [ ] Comment Removal
- [x] Tag / Category Editing
- [ ] Marking Mods as deprecated / abandoned
- [x] Completely disabling mods if found to be harmful (unapproval)
- [x] GDPR account removal / sanitization of accidentally disclosed PII
- [x] account renames
- [ ] username / mod name blacklist

**Comment by sdaugherty** [comment]
putting this up so it's not forgotten, but likely this should be split into several issues when it's actually worked

**Comment by Geometrically** [comment]
Approval/Rejection of mods has been completed!

**Comment by diabolical17** [comment]
`account renames` is possible.

**Comment by wafflecoffee** [comment]
Since this is a monstrous issue, it's been split up into several more manageable tasks and is being tracked internally as MOD-84 through MOD-94.
