### ISSUE TITLE
500 Internal error page when navigating to /moderation

### ISSUE THREAD

**Issue by MagnusHJensen** [modrinth/knossos#1003]
### Describe the bug

When navigating to `/moderation` and not being a Moderator or Admin, results in a 500 Internal server Error page.
This happens due to the axios call to retrieve projects that need moderation, returns 401 which is not handled properly in the promise.all call.

### Steps to reproduce

1. Go to https://modrinth.com/moderation
2. See 500 page

### Expected behavior

To see either a 401 Forbidden page, or just a 404 since that route "should not" exist for regular users.

### Additional context

Prod:
![image](https://user-images.githubusercontent.com/32039051/219874151-e1003064-6f75-42d5-a849-61fb6de448af.png)

Local dev:
![image](https://user-images.githubusercontent.com/32039051/219874177-ebfd9bd5-f716-4454-8335-7e95383b63e9.png)

**Comment by triphora** [comment]
I don't really see how this is a problem - you're not supposed to be accessing this at all

**Comment by Minenash** [comment]
That's... not the point? Sites should have proper error messages anyways

**Comment by Andre601** [comment]
Kinda agree.
If that is a site a normal user isn't supposed to access should a more fitting error code happen here. Preferrably something along the lines of `401 Unauthorized` or `403 Forbidden`

A `500 Internal Server ERROR` gives the impression the site is unable to even handle a simple case of a user trying to access a page they shouldn't.

**Comment by Minenash** [comment]
And it's not even that the correct error isn't being used, something is returning a 401, but for some reason the function crashes instead of it being properly sent to the user

**Comment by MagnusHJensen** [comment]
I agree, definitely not user friendly.

**Comment by MagnusHJensen** [comment]
But it’s also a code smell. That errors are not being handled properly, which by looking at the code is true, it just assumes a correct 2xx response.

**Comment by triphora** [comment]
This is still a non-issue though. I don't understand why anyone is worried about an error that they will never encounter unless they are trying to access something they shouldn't be accessing.
