### ISSUE TITLE
Public domain licences not counted as open source

### ISSUE THREAD

**Issue by Secret-chest** [modrinth/knossos#1009]
### Describe the bug

Licences such as the CC0, Unlicense, WTFPL and others, used by some mods, are not counted by the open source filter.	

### Steps to reproduce

1. Go to the Mods page
2. Enable the 'open source' filter
3. Search for 'no chat reports' (example, there are many more), which is WTFPL, should lead you to [this](https://modrinth.com/mod/no-chat-reports), but it's not possible to find it

### Expected behavior

Be able to see CC0, WTFPL and Unlicense licensed projects when selecting the open-source filter

### Additional context

I love Modrinth lol
Much better than Curseforge

**Comment by MagnusHJensen** [comment]
Unlicensed != Open Source.
Unlicensed by default falls under exclusive copyrights (ARR (All Rights Reserved))
https://choosealicense.com/no-permission/

**Comment by MagnusHJensen** [comment]
My bad, unlicensed is the license. I thought you meant it did not have a license.

**Comment by triphora** [comment]
The library we use uses this list: https://opensource.org/licenses/

OSI has been controversial in the past for not allowing CC0, but the OSI definition is the closest thing we have to any "standard" definition.

**Comment by Minenash** [comment]
Is it possible to have a list of licenses also considered open source for modrinth?  I doubt when people use the open source only box, they care about if it's open source according to OSI, as long as it has available source and allows people to freely use, modify, and redistribute which is what most people thing of when they think open source

**Comment by triphora** [comment]
Who are we to create a new definition of what is open source or not?

**Comment by Minenash** [comment]
To match expectations of users?

I can't think of any reason someone would want to search for open source projects and not want mods with those licenses included

If you take don't want to change what defines open source, you could change the checkbox to "Open Source and Public Domain" or something like that.

**Comment by triphora** [comment]
It's not a matter of public domain not being open source—it's a matter of the licenses in question not fitting the OSI definition. CC0 isn't OSI-approved because it doesn't give patent rights, iirc.

**Comment by Secret-chest** [comment]
Another option would be to just bring back the old licence filter.

**Comment by triphora** [comment]
The discussion was already had in #828 about why this isn't possible. Likely the only way the ability to search for a license individually will be the future addition of modrinth/.github#15.
