### ISSUE TITLE
Allow featuring versions while creating them

### ISSUE THREAD

**Issue by Pomi108** [modrinth/knossos#1014]
### Is your suggested enhancement related to a problem? Please describe.

Unless I'm misremembering, it used to be possible to feature a version during the creation process before the Create Version page got redesigned. This isn't possible anymore, meaning I have to go back and edit the version to feature it after it's been published.

### Describe the solution you'd like

There should be a button to feature the version directly on the Create Version page.

**Comment by triphora** [comment]
Out of curiosity, what is your use case where you need to manually feature your versions?

**Comment by Pomi108** [comment]
For every pack update, Faithful releases packs for every supported Minecraft version. There's A LOT of them, and if I just leave it on auto-feature, Modrinth shows the previous Faithful update in the sidebar as well.

**Comment by triphora** [comment]
It shows the latest release for each major Minecraft version.

**Comment by Pomi108** [comment]
Oh wait, I realised what the issue was with Faithful – we stopped supporting 1.19.2 in December, that's why it was still showing the release from October.

Nonetheless, I'm gonna keep this issue open, since I think this would be an useful feature to have and wouldn't harm anything.

**Comment by triphora** [comment]
Merging this issue into modrinth/.github#52
