### ISSUE TITLE
The new mobile bar doesn't allow space for home bar (ios)

### ISSUE THREAD

**Issue by TruMiner** [modrinth/knossos#1031]
### Describe the bug

It doesn't allow space anymore

### Steps to reproduce

1. Go to modrinth on mobile
2. see that the bar is ~1 pixel from the icon.

### Expected behavior

should be a few more pixels higher

**Comment by TruMiner** [comment]
![image](https://user-images.githubusercontent.com/106455196/224167674-20073a08-4eda-4713-9917-00a64af98906.png)

**Comment by TruMiner** [comment]
after further investigation, it seems that this only applies on some 3rd party browsers;

safari has a built in safe area but it seems that 3rd party browsers are allowed to remove that so if you are using firefox or another browser that does not have built in safe area, it will be like that.

**Comment by Prospector** [comment]
hmm, those browsers must not be setting `env(safe-area-inset-bottom)` correctly then, looks like Nuxt 3 still uses it.

**Comment by Prospector** [comment]
Seems like a browser bug, nothing we can do about it
