### ISSUE TITLE
Suggestion: Client/Server Categories

### ISSUE THREAD

**Issue by itsVyasi** [modrinth/knossos#107]
I'm suggesting new categories for mods intended for only client usage or only server usage, and maybe unmarked mods show  with either to help visibility, but are sorted last.

**Comment by Sollace** [comment]
+1

I'd like the same thing, though my thought was instead of categories make it a dropdown like what we already have for the MC version. Let it be a selection between Client/Server/Both

**Comment by Geometrically** [comment]
Duplicate of #100

**Comment by itsVyasi** [comment]
Oops, somehow missed the other one, my bad.
