### ISSUE TITLE
Download directly from search

### ISSUE THREAD

**Issue by dussc** [modrinth/knossos#108]
This is a pretty minor suggestion imo. 

The other day I was helping a friend download a few optimization mods off modrinth and thought it would be nice to have a direct download on each mod from the search, since I already new which mods were needed and their names.

**Comment by wafflecoffee** [comment]
This seems like it could go wrong in too many ways. It encourages users to simply glance over the summary and download it, disregarding anything relating to loaders, Minecraft version, etc. I'm going to keep this open to get feedback from others, though.

**Comment by RedstoneWizard08** [comment]
I will be adding a download button to search result entries in my PR for the SvelteKit rewrite.

**Comment by Prospector** [comment]
I don't think this is a good idea, it will likely result in users downloading the wrong versions for the wrong mod loader or Minecraft versions, and also means the user will not read the description or be able to view changelogs or anything.
