### ISSUE TITLE
New Category: Audio

### ISSUE THREAD

**Issue by sternschnaube** [modrinth/knossos#1107]
### Is your suggested enhancement related to a problem? Please describe.

It's currently not possible to search explicit for audio related mods of Minecraft.
I think this category deserves its place.

**Comment by Wanesty** [comment]
"**Immersion**" could be more appropriate imo since most Immersion-type mods currently are under the **Adventure** category (sometimes **Adventure**+**Decoration**+/**Utility**)

**Comment by Prospector** [comment]
I like Immersion, it allows for more than just sound, you can probably filter further with search queries.

**Comment by triphora** [comment]
Merging this issue into https://github.com/orgs/modrinth/discussions/105#discussioncomment-6032869
