### ISSUE TITLE
A visual markdown editor w/ formatting buttons

### ISSUE THREAD

**Issue by Gaming32** [modrinth/knossos#1121]
### Is your suggested enhancement related to a problem? Please describe.

Not everyone knows markdown. Especially people who haven't done much programming, like resource pack devs.

### Describe the solution you'd like

Use a WYSIWYG markdown editor for the markdown editor. I've found [an open-source one](https://github.com/Ionaru/easy-markdown-editor) that you could use.

**Comment by Prospector** [comment]
What you linked isn't a WYSIWYG editor, but yeah I've been wanting to implement something similar to that for a while. Was planning on making my own though that better fits our needs

**Comment by Gaming32** [comment]
What I linked is a hybrid WYSIWYG/raw editor, which is really what I meant by WYSIWYG.

**Comment by Prospector** [comment]
It's not WYSIWYG, but we have implemented a new editor which allows people to use formatting with buttons if they're unfamiliar with them. I think this is as far as we're going to take this for now.
