### ISSUE TITLE
"Allow later revisions of this license" checkbox can't be clicked

### ISSUE THREAD

**Issue by Astralchroma** [modrinth/knossos#1125]
### Describe the bug

"Allow later revisions of this license" checkbox can't be clicked

### Steps to reproduce

Select a license where the "Allow later revisions of this license" checkbox shows and attempt to click it.

### Expected behavior

The checkbox should be ticked

**Comment by MMK21Hub** [comment]
Can confirm. This can be reproduced with the **GNU Affero General Public License v3** licence.

**Comment by TeaEffTeu** [comment]
Can also confirm. This occurs for all of the GNU licenses listed in the dropdown.

**Comment by triphora** [comment]
This is fixed now.
