### ISSUE TITLE
Team member editing form locks up when role is set to Owner

### ISSUE THREAD

**Issue by BasiqueEvangelist** [modrinth/knossos#113]
![image](https://user-images.githubusercontent.com/72868417/110030536-ee0dda00-7d46-11eb-89d9-de1f6e13fc6a.png)

**Comment by Geometrically** [comment]
This is intended. The Owner is not supposed to be edited, since it has all permissions in a mod.

**Comment by BasiqueEvangelist** [comment]
In the screenshot, I am the owner and Jetsparrow is co-owner. When I write "Owner" in the role text box, the form locks up.
