### ISSUE TITLE
The followed project list does not show loaders

### ISSUE THREAD

**Issue by HyperSoop** [modrinth/knossos#1156]
### Describe the bug

Projects displayed in the followed projects list do not show their loaders like they do in search

### Steps to reproduce

Go to https://modrinth.com/settings/follows

### Expected behavior

Projects are displayed like they are on search pages

**Comment by Minenash** [comment]
If a PR was created to fix this, would it be accepted?

**Comment by Prospector** [comment]
Not worth it, will be overhauled soon anyway

**Comment by Prospector** [comment]
No longer an issue
