### ISSUE TITLE
I'm not able to upload icon for my Datapack

### ISSUE THREAD

**Issue by MatinButNot** [modrinth/knossos#1172]
### Describe the bug

When I upload an image and save settings, I get the success message. But when I refresh, nothing has changed

### Steps to reproduce

Setting an icon for a Datapack

### Expected behavior

Just work :)

**Comment by MMK21Hub** [comment]
Hi! I haven't been able to reproduce this on production or staging.modrinth.com: setting and replacing datapack icons works fine. Are there any other prerequisites I'm missing? Does the issue persist across different browsers?
