### ISSUE TITLE
Licensing & self hosting?

### ISSUE THREAD

**Issue by tranquillity-codes** [modrinth/knossos#1197]
### Is your suggested enhancement related to a problem? Please describe.

Since the assets are All Rights Reserved, can the project not be self-hosted unless one does a rebrand? What about trademarks? I cannot find any legal information about self-hosting Modrinth.

### Describe the solution you'd like

Most preferable would be to fully open source the project, or at least describe exactly what is necessary for self hosting. A branding option at build time would be great (like how Mozilla Firefox does it).

**Comment by Prospector** [comment]
Correct, if you host your own Knossos instance you must remove all Modrinth branding. They're trademarked and copyrighted.

**Comment by Minenash** [comment]
Just for future reference, what counts as branding? Ofc any mentions or logos of modrinth itself, and general assets, but does the accent color count? It's definitely a part of modrinth's branding, but not sure if it's a required change

**Comment by Prospector** [comment]
All of these variables (light and dark) are brand colors and should be changed:

  --color-brand-green
  --color-brand
  --color-brand-highlight
  --color-brand-shadow
  --color-brand-inverted
  --color-special-red
  --color-special-orange
  --color-special-green
  --color-special-blue
  --color-special-purple
  --color-special-gray

Legally, I don't believe these (including the green) are trademarked, but we'd ask you to change them and potentially might have a legal case for them being unregistered trademarks, at least for the green color.
