### ISSUE TITLE
Project type for plugins is "mod" 

### ISSUE THREAD

**Issue by NikSneMC** [modrinth/knossos#1209]
### Describe the bug

On any Bukkit/Spigot/Paper/Folia/BungeeCord/Velocity/Waterfall plugin (only plugin!) page project type is "mod" 

### Additional context

![example_for_discordsrv](https://github.com/modrinth/knossos/assets/88781618/11736ec2-f3ea-4581-81dc-818293644122)

**Comment by Nim1com** [comment]
Possibly close this as looking up that same project currently shows Plugin.

**Comment by Prospector** [comment]
yup, this was fixed
