### ISSUE TITLE
Cannot drag and drop zip files into a datapack project page

### ISSUE THREAD

**Issue by ejektaflex** [modrinth/knossos#1221]
### Describe the bug

![image](https://github.com/modrinth/knossos/assets/23628421/9e32d89b-e17b-4430-930b-7e0ac0fd71c9)

In the image above, it seems impossible to drag and drop a zip file anywhere onto this page, whether it be the page itself, the area that explains that you can drop it, or the button for uploading.

### Steps to reproduce

1. Create a data pack project.
2. Try to drag and drop a zip file.

**Comment by MMK21Hub** [comment]
Hi! I'm unable to reproduce this issue in Firefox 116, Zorin OS 16.2 and GNOME Shell 3.38.4. Dragging any zip file into the viewport on the Versions page successfully opens the version creation page. May I ask what environment you're using?

![Dragging the icon of a zip file into the Versions page of a project, with a overlay showing that the file will be accepted](https://github.com/modrinth/knossos/assets/50421330/88c90013-b6d8-4d21-baec-625322a83f87)

**Comment by ejektaflex** [comment]
Yeah, that doesn't show up for me. I'm using Firefox 115.0.2 (current stable version) with Windows 11 v10.0.22000.

It doesn't seem to work on Firefox Nightly 117.0a1 either.

Interesting, ever since I last tested, I'm not able to use the drag & drop *anywhere* on the website, whether it's Firefox, FF Nightly or Chrome. It still works if I drop the file on top of the button, but otherwise it never shows up.

**Comment by ejektaflex** [comment]
It seems to work fine with JAR files when I drag them into any of my projects, but ZIP files won't show the drop-zone or work.

**Comment by MMK21Hub** [comment]
In that case, it could be that the file you're attempting to drop isn't considered a zip file for some reason. I say this because Modrinth will let you drop any file type directly onto the "Upload a version" button (this is actually built-in browser behaviour), but if you're dropping elsewhere on the page, it only responds to zip files.

Perhaps your file is actually a `.rar`/`.7z` or similar file type (in that case, picking it manually will result in an error upon creating the version)?

**Comment by ejektaflex** [comment]
It's definitely just a zip file. I could right click on any file in my file explorer and then send it to a compressed zip folder then drag it over and it won't work. 🫠

**Comment by triphora** [comment]
Unable to reproduce. Zip files work fine for me.

**Comment by ejektaflex** [comment]
I definitely still can't drag and drop into Modrinth. I tested with Firefox, Chrome and Edge, and none of them worked when dragging in a simple `.zip` file.

Other sites like Google Drive let me drag and drop just fine.

Perhaps it's related to the operating system? I'm using Windows 11 build 22000.2295.

**Comment by triphora** [comment]
If another Windows user is able to confirm, I'm happy to reopen it.

**Comment by ejektaflex** [comment]
I can also confirm that it does not work on my secondary desktop, nor my Windows laptop, which are both on Windows 10.

It works fine on my Macbook.

**Comment by qtchaos** [comment]
.zip drag and drop works for me, tested with Firefox version 116.0.3 on Windows 10
