### ISSUE TITLE
Version table row is super-tall when including lots of version info

### ISSUE THREAD

**Issue by egeesin** [modrinth/knossos#124]
As you can see from this [example](https://modrinth.com/mod/fabric-discord-link/versions), rows might need overflowing or max-width declarations for situations like this.
![image](https://user-images.githubusercontent.com/8004972/112759555-304fd180-8ffc-11eb-85b5-bc768e2dcfed.png)

**Comment by Minenash** [comment]
(Most of these have been suggested, just nice to put it with the issue)
One solution would be to have the top few listed, then a `...` then when that section is clicked, extends the card to show the versions.

Another would be compacting them, a few ways:
- If the mod supports all 'patch' versions of a minor version (1.16, 1.16.1, ..., 1.16.5), then the `patch` can be replaced with an `x` (1.16.x)
- If it doesn't match the above, but does support all release versions between two (1.15.2 - 1.16.5 or 1.16.2-1.16.5), then it could be replaced with a range `1.16.2 - 1.16.5`
- If the card can expand like suggested above, it includes numerous snapshots, use `1.16 Snapshots` and when expanded show the actual snapshot versions

**Comment by wafflecoffee** [comment]
This is fixed in [the latest UI](https://knossos-g9dellpil-emmaffle.vercel.app/mod/fabric-discord-link/versions)!
