### ISSUE TITLE
Use en dash for versions range instead of em dash

### ISSUE THREAD

**Issue by zefir-git** [modrinth/knossos#1245]
### Is your suggested enhancement related to a problem? Please describe.

En dash is used to show ranges in numbers or dates (in this case versions). Currently, an em dash is used, which is incorrect. The em dash is a mark that can be used to replace commas, parentheses, colons, and semicolons.

| name | symbol |
| - | - |
| em dash (current, wrong) | `—` |
| en dash (correct) | `–` |

### Describe the solution you'd like

Use en dash. `–`

**Comment by falseresync** [comment]
I mean. This is probably the least problematic thing out there lol, there’s literally no visual difference in many fonts, why bother

**Comment by zefir-git** [comment]
> Feel free to make a PR

Sure, I can do that. Can you please confirm this is it:

https://github.com/modrinth/knossos/blob/91e1eff763b103bfcdb33ea9f2dbe9cdf417e397/plugins/shorthands.js#L317

**Comment by triphora** [comment]
yeah
