### ISSUE TITLE
Fixed place for search input bar across multiple pages

### ISSUE THREAD

**Issue by BikrantJung** [modrinth/knossos#1256]
### Is your suggested enhancement related to a problem? Please describe.

When we click on either of the tabs (mods, resource packs or datapacks) on top menu, we can find search bar and sorting input field. And when we click on specific mod or navigate to page /mod/{mod_name} the search bar is no longer there, we have to go back a step each time we want to search for different mod or packs. 

### Describe the solution you'd like

It would be easier to search for multiple mods if that search bar is persisted in each pages even after entering the page for specific mod so we don't have to go back to search for another mod.

**Comment by triphora** [comment]
Sorry, but this just doesn't really work with the layout of our pages. Besides, Modrinth doesn't exist *exclusively* to search for projects; there are several other aspects to the site that would be overshadowed and left to the wayside if this were to be implemented, and simply doesn't bode well for our design language.
