### ISSUE TITLE
Error 400 on Social Login with GitHub

### ISSUE THREAD

**Issue by OfficialCRUGG** [modrinth/knossos#1261]
### Describe the bug

![image](https://github.com/modrinth/knossos/assets/25248999/7db14e07-071c-47d6-b515-cdeec3e5b0fa)

Getting this error when I try to sign up with GitHub on the staging instance. What is this supposed to mean?
Also why does it say Launcher? This is the website...

### Steps to reproduce

1. Sign in with GitHub

### Expected behavior

Be able to register normally

### Additional context

On the staging site

**Comment by triphora** [comment]
It says it right there, user email/account is already registered on Modrinth. Support can be found in our Discord, not on GitHub: https://discord.gg/modrinth

**Comment by OfficialCRUGG** [comment]
But... I am trying to log in... I know I am registered... This is a bug, not something for support.

**Comment by triphora** [comment]
The issue doesn't provide enough context, and even if it did, this would be a labrinth bug, not a knossos bug. Please join the support channels and we will direct you as to whether this should be reopened.
