### ISSUE TITLE
Save changes button is misplaced

### ISSUE THREAD

**Issue by RealmKebab** [modrinth/knossos#1263]
### Describe the bug

![image](https://github.com/modrinth/knossos/assets/73048123/b557f5cc-dcc5-4463-a6c1-fc884bc1fa60)

### Steps to reproduce

1. Write a very long description on your mod (this is a modpack fyi)
2. Go to your settings to edit it
3. The thing happens

### Expected behavior

The description being correctly put above the "Save changes" button

**Comment by RealmKebab** [comment]
yeah this is not hte right place

**Comment by triphora** [comment]
This is the right place

**Comment by RealmKebab** [comment]
my bad, i just didn't know since it wasn't clear enough

**Comment by ThatGravyBoat** [comment]
Just some information on why this is happening is because both knossos and omorphia use the same global class name so the omorphia one conflicts and sets the hight to 10rem 
https://github.com/modrinth/omorphia/blob/master/lib/assets/styles/classes.scss#L624

**Comment by RealmKebab** [comment]
any updates?

**Comment by triphora** [comment]
It's fixed now

**Comment by RealmKebab** [comment]
Okay

**Comment by enderpirate98** [comment]
It just happened to me but I will try again

https://modrinth.com/modpack/hotf

**Comment by enderpirate98** [comment]
The button is still in the right place but it is greyed out.

**Comment by enderpirate98** [comment]
Nvm after I put a few more words and it let me submit!
