### ISSUE TITLE
Error when refreshing notifications page

### ISSUE THREAD

**Issue by Bartolumiu** [modrinth/knossos#1309]
### Describe the bug

When you refresh the notifications page, an error occurs.

### Steps to reproduce

1. Log into your Modrinth account. (If not already logged in)
2. Click on the bell icon (it should load normally)
3. Refresh the page

### Expected behavior

The page should keep the same:

![Expected behavior img](https://github.com/modrinth/knossos/assets/42890541/99acd0e2-a04c-4573-9950-773eeba95b37)

### Additional context

What actually happens:

![Actual behavior img](https://github.com/modrinth/knossos/assets/42890541/36147c3a-fe6a-4d93-bc1c-8e97d3901396)

**Comment by Bartolumiu** [comment]
Video of the issue:

[Issue vid](https://github.com/modrinth/knossos/assets/42890541/5fc3f092-4203-4344-90f9-885e8cc96d5c)

**Comment by Bartolumiu** [comment]
Just noticed that the bug also happens when reloading the Dashboard overview page at [https://modrinth.com/dashboard](https://modrinth.com/dashboard)

**Comment by sumone-lol** [comment]
Had the same error but now if I refresh, it leads to the sign in page. But then if i click on the notification badge on the top right, it shows this instead 
![image](https://github.com/modrinth/knossos/assets/88620982/491924f1-a3d7-46db-b482-6514ca14ec35)

**Comment by Bartolumiu** [comment]
Apparently fixed as of Oct. 12
