### ISSUE TITLE
Website content is doubled

### ISSUE THREAD

**Issue by bestsoft100** [modrinth/knossos#1318]
### Describe the bug

The entire content of the website is doubled, see for yourself in the video I attached

https://github.com/modrinth/knossos/assets/49400900/cb119a9b-ec4d-4a03-a9fa-668d1a067842

### Steps to reproduce

Go on Google
Search for "minecraft rei"
Click on "Roughly Enough Items (REI) - Minecraft Mod"

When simply opening "https://modrinth.com/mod/rei" it doesn't happen.
In incognito mode it doesn't happen.

### Expected behavior

Website content appears only once

### Additional context

Windows 10
Google Chrome
Logged in via GitHub

**Comment by Nitrrine** [comment]
Hello, I'll try to reproduce it and fix it!

**Comment by triphora** [comment]
Unable to reproduce, try clearing your browser cache and refreshing
