### ISSUE TITLE
CAPTCHA error

### ISSUE THREAD

**Issue by ubionexd** [modrinth/knossos#1353]
### Describe the bug

When logging in using a password manager on mobile, a CAPTCHA error is shown. Resubmitting the form wouldn't work either.
![Screenshot_2023-09-03-09-08-45-032_com brave browser-edit](https://github.com/modrinth/knossos/assets/70473378/c1b952fc-08ef-43c3-95aa-d4fb88deb75c)

### Steps to reproduce

1. Go to the Modrinth login page
2. Autofill your creditentials using a password manager with Gboard
3. Click login
4. The error is shown

### Expected behavior

It lets you log in.

### Additional context

Android 13
Brave Browser
Bitwarden
Gboard

**Comment by Nukecraft5419** [comment]
I am also experiencing the same problem I from PC but always with Brave have you found a solution yet?

**Comment by ubionexd** [comment]
> I am also experiencing the same problem I from PC but always with Brave have you found a solution yet?

Nope.

**Comment by Nukecraft5419** [comment]
Strangely it works now I guess you have to close and reopen the browser or clear the browser cache

**Comment by MMK21Hub** [comment]
I've also noticed this when using Bitwarden, with it set to autofill on page load.
- Firefox 118.0b3 (64-bit)
- Zorin OS 16

**Comment by Nukecraft5419** [comment]
Have you tried filling in the fields manually to see if it's auto-filling the password managers I use Proton Pass and I also had that problem from PC

**Comment by rogama25** [comment]
Just happened to me when filling the email field with Chrome's auto suggestion but inputting the password manually because it wasn't saved. You need to edit both fields to be able to login

**Comment by Nukecraft5419** [comment]
The problem to me for now has not happened anymore from PC I don't know if still today after a few months that problem still exists although I have noticed that rarely when the API is used a lot or there are a lot of requests it gives that error some times I know that modrinth went offline with the API

**Comment by Brittank88** [comment]
The captcha is an invisible 5-10 seconds captcha where you just have to wait on the page that long before submitting. Have been talking to support about this being made more clear for users after suffering from it myself.

**Comment by MMK21Hub** [comment]
Thanks for sharing that explanation! It's a shame to see the log-in page straying away from Modrinth's usual transparent, user-first attitude.

**Comment by Brittank88** [comment]
> Thanks for sharing that explanation! It's a shame to see the log-in page straying away from Modrinth's usual transparent, user-first attitude.

I agree - it even seems like some of the support members were potentially unaware that this was an issue that was already lodged. They're a good team and dedicated to Modrinth so it feels weird that this is just overlooked.

I'm unsure why it would be so hard to introduce a timer to the UI... like any other site that does a similar thing.

**Comment by Jannyboy11** [comment]
I also experience this issue since september last year.

**Comment by brawaru** [comment]
On desktop you can install Privacy Pass client by Cloudflare to force a visible CAPTCHA: https://github.com/cloudflare/pp-browser-extension.

**Comment by Jannyboy11** [comment]
> On desktop you can install Privacy Pass client by Cloudflare to force a visible CAPTCHA: https://github.com/cloudflare/pp-browser-extension.

That is a workaround, not a solution. This workaround has particularly bad UX too.
