### ISSUE TITLE
Allow disabling Auto-Feature

### ISSUE THREAD

**Issue by RealmKebab** [modrinth/knossos#1359]
### Describe the solution you'd like

i'd like disabling auto-feature, it clears up the mess of multiple versions extending the whole page for no reason at all

**Comment by RealmKebab** [comment]
edited since most of the things didnt at all match up about the description :yipe:

**Comment by Prospector** [comment]
You can disable auto-featuring by manually featuring versions. it's a lot of effort to maintain but if you want to, you may.
