### ISSUE TITLE
Improve Markdown Preview in Report

### ISSUE THREAD

**Issue by Phoenix-Starlight** [modrinth/knossos#1404]
### Is your suggested enhancement related to a problem? Please describe.

The preview currently buries link and makes it appear as plaintext.

### Describe the solution you'd like

It should appear as a link, like with `<a>` tags

**Comment by Mysterious-Dev** [comment]
Do you have any screenshots to show us the problem in more detail?

**Comment by Phoenix-Starlight** [comment]
![modrinth com_mod_fabric-api (1)](https://github.com/modrinth/knossos/assets/64714532/0a468ba9-847f-44e9-98d2-a73b95676e4c)
![modrinth com_mod_fabric-api (2)](https://github.com/modrinth/knossos/assets/64714532/5a534e19-d241-41a2-b300-922ff7207e9e)
Attached are two screenshots from Google Chrome `Version 117.0.5938.132 (Official Build) unknown (64-bit)`

**Comment by Prospector** [comment]
Fixed with the new reporting experience
