### ISSUE TITLE
Automatic markdown links don't include trailing '!'s

### ISSUE THREAD

**Issue by CodeF53** [modrinth/knossos#1465]
### Describe the bug

Mods can have ids with `!` in them, but the markdown processor doesn't include `!` in links automatically

### Steps to reproduce

Paste `https://modrinth.com/mod/flint-overflow!` into any markdown field on the site and press preview.

### Expected behavior

Input of
```md
https://modrinth.com/mod/flint-overflow!
```
To turn into
```html
<a href="https://modrinth.com/mod/flint-overflow!">https://modrinth.com/mod/flint-overflow!</a>
```

But actually it gives
```html
<a href="https://modrinth.com/mod/flint-overflow">https://modrinth.com/mod/flint-overflow</a>!
```
Which gives a 404 not found.

### Additional context

Annoyed me when I was reporting `flint-overflow!` for invalid metadata.

**Comment by DAQEM** [comment]
This is the default behaviour of [Markdown It](https://github.com/markdown-it/markdown-it) which is used by Knossos to convert markdown to HTML. 
This can be seen in [this example](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22https%3A%2F%2Fmodrinth.com%2Fmod%2Fflint-overflow!%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D).

Even GitHub doesn't support this feature as show here:
https://modrinth.com/mod/flint-overflow!

**Comment by triphora** [comment]
Yup, this is a wontfix. It might be better to suggest that we remove the ability to have special characters in slugs at all.
