### ISSUE TITLE
Sign in button doesn't work from all pages

### ISSUE THREAD

**Issue by supersaiyansubtlety** [modrinth/knossos#151]
Clicking the 'Sign in with GitHub' button from 
[https://modrinth.com/mods?q=&f=categories%3Afabric&s=updated](https://modrinth.com/mods?q=&f=categories%3Afabric&s=updated) 
takes me to 
[https://modrinth.com/mods?q=[TOKEN LEAKED](https://modrinth.com/mods), 
which doesn't let me login. 

The sign in button works fine from [https://modrinth.com/](https://modrinth.com/). 

Also I don't stay logged in when I go to my bookmark of the first page I linked, but I suspect that's the same root issue.

**Comment by Geometrically** [comment]
Please revoke your Modrinth token ASAP, you just leaked it in this issue

**Comment by supersaiyansubtlety** [comment]
oh oops, thanks

**Comment by Kneelawk** [comment]
Steps to reproduce:

1. Open the Modrinth mods page, 'https://modrinth.com/mods', making sure to be logged in with github.
2. Type something in the search field.
3. Click your user dropdown in the top right corner and select Log Out.
4. Click the 'Sign In with GitHub' button that is now in the top right corner.
5. Notice that your token has been appended to the search term in the search field and you are still not logged in.

**Comment by Redblueflame** [comment]
It's fixed now.

**Comment by supersaiyansubtlety** [comment]
It's still happening for me.
Is the update not live yet?

**Comment by supersaiyansubtlety** [comment]
Refreshing the page no longer logs me out, but I can still only log in from [https://modrinth.com/](https://modrinth.com/)

**Comment by supersaiyansubtlety** [comment]
Still having the same problem.

**Comment by wafflecoffee** [comment]
The fix (modrinth/labrinth@bc983162f32f4f958d78cc9c10f5a7fb255b2147) is not live yet.

**Comment by venashial** [comment]
You can test the staging instance, https://staging.modrinth.com/mods

**Comment by supersaiyansubtlety** [comment]
Oh thanks, didn't realize. 
The staging version does indeed fix it.
