### ISSUE TITLE
Projects in an org should show on the profiles of org members.

### ISSUE THREAD

**Issue by woodiertexas** [modrinth/knossos#1511]
### Is your suggested enhancement related to a problem? Please describe.

Projects in orgs don't show on user profiles currently.

### Describe the solution you'd like

Org projects get listed on every member's profile and ideally with a way to identity which org owns said project at a glance.

**Comment by Pyrofab** [comment]
On the other hand, not everyone in an org actually runs every project. I think the project should only display on your profile when you have a custom role or some specific (possibly new ?) permission on that project's page.

**Comment by Lgmrszd** [comment]
Should be added that current behavior is somewhat inconsistent

For example, https://modrinth.com/mod/timelock is owned by ModFest Organization, but shows up on ModFest User profile

The mod https://modrinth.com/mod/anshar owned by organization consisting of me and my friend, doesn't show up on my profile

(Actually, as I was writing this, it did show up! But it seems that "Override values" toggle on project members settings caused that? I toggled it on but the mod did not appear on my profile initially. After toggling it off, the mod disappeared again, and after toggling on it didn't appear yet)

**Comment by Prospector** [comment]
The way it works is it only shows up if the user's permissions are overridden on a project, so anyone with default org permissions is collapsed under the org entry. However, this obviously has problems since the Owner can never show up as the permissions of the Owner can't be overridden

**Comment by Prospector** [comment]
This is resolved since owners can now be overridden on projects
