### ISSUE TITLE
Searching dosen't return seached mod

### ISSUE THREAD

**Issue by Player505** [modrinth/knossos#1521]
### Describe the bug

When searching for a mod on modrinth the specific mod doesn't show up.
The mod does exist on modrinth as I can find it though google.

### Steps to reproduce

1. Search for a mod in modrinth e.g. Condensed Creative
2. Dosen't appear
3. Search for a mod in google e.g. Condensed Creative
4. Linked to modrinth page

### Expected behavior

Able to search for mods within modrinth

**Comment by RDKRACZ** [comment]
Same for modpacks:
https://modrinth.com/modpack/all-of-fabric
https://modrinth.com/modpacks?q=all+of+fabric

https://modrinth.com/modpack/all-the-fabric-5
https://modrinth.com/modpacks?q=all+the+fabric

**Comment by Tomate0613** [comment]
I think this might be a problem with spaces. When searching for "birds" my mod shows up, but as soon as I search for "birds b" it is no longer in the list.

**Comment by Tomate0613** [comment]
This seems to be fixed
