### ISSUE TITLE
Analytics rendering multiple y points on an x graph for downloads

### ISSUE THREAD

**Issue by ridglef** [modrinth/knossos#1582]
### Describe the bug

Analytics rendering multiple y points on an x graph for page views
![image](https://github.com/modrinth/knossos/assets/126202739/1dc3fad0-f0d5-4be6-8b3a-0f7040ed1640)

### Steps to reproduce

Visit https://modrinth.com/dashboard/analytics

this may be an isolated bug to me or a few others

### Expected behavior

One y point per x point on the graph

**Comment by ridglef** [comment]
Wrote the wrong  analytic - page views not downloads

**Comment by jakjakob** [comment]
similar - 
![image](https://github.com/modrinth/knossos/assets/118139800/5c1ffbfa-7edb-4988-b241-74b55c844ef8)
the curves are a bit buggy (they go backwards in certain points)

**Comment by BradBot1** [comment]
I am also experiencing this issue but with the total downloads area

![image](https://github.com/modrinth/knossos/assets/45739045/adf498d6-f22c-4e09-b23c-116d15478156)

**Comment by M0on9** [comment]
Im also having the same issue in the downloads field
![Analytics field has a stroke i guess](https://github.com/modrinth/knossos/assets/107826658/06cb25a9-fbaa-4559-a086-708b947fe658)

**Comment by AwesomeBFM** [comment]
![image](https://github.com/modrinth/knossos/assets/55819926/2719acfb-c5e3-4775-879a-e17755bc7424)
I have seen this too, on Firefox for iOS, Firefox for Windows, and Firefox for Linux

**Comment by JosiahFu** [comment]
Tested on Firefox & Chrome on Linux, doesn't seem specific to one browser

**Comment by jakjakob** [comment]
Can confirm that isn't browser specific, my screenshot is from Safari macOS

**Comment by Caotenhoch2** [comment]
Still experiencing the same issue
![Screenshot 2024-02-17 at 20-01-45 Modrinth](https://github.com/modrinth/knossos/assets/65490656/00ea2961-67b0-4ee3-a18e-e10e1395cb44)

**Comment by yunfachi** [comment]
Becomes normal after resize event
```js
window.dispatchEvent(new Event('resize'));
```

**Comment by Switch672** [comment]
> Becomes normal after resize event
> 
> ```js
> window.dispatchEvent(new Event('resize'));
> ```

Issue with Vue's server side rendering?
