### ISSUE TITLE
COPYING.md possibly shows outdated information

### ISSUE THREAD

**Issue by PlayerXYT** [modrinth/knossos#1585]
### Describe the bug

/COPYING.md states ©2020-2023, it's 2024

### Steps to reproduce

Open /COPYING.md in source code

### Expected behavior

Shouldn't it state ©2020-2024?

**Comment by OriloyeEmerald** [comment]
I will love to look at this issue. Please can you guide me on how to go about it?

**Comment by Martins100-Tmd** [comment]
Can I get assigned this issue?

**Comment by triphora** [comment]
Do not spam this issue with meaningless commentary. Either do it or don't.
