### ISSUE TITLE
Allow for the OLED colors to be used with the "sync with system" option

### ISSUE THREAD

**Issue by Aeldit** [modrinth/knossos#1672]
### Is your suggested enhancement related to a problem? Please describe.

Currently, we can select the OLED colors only as dark theme for the toggle with light/dark. However, the sync with system option still uses the default dark theme

### Describe the solution you'd like

I would like to be able to select the OLED colors for the sync with system option too

**Comment by Prospector** [comment]
Hmm, it should use it if it's set to your preferred dark theme...

**Comment by Aeldit** [comment]
Well it switches back to the default dark when changing the system theme

**Comment by Aeldit** [comment]
I just tested it on computer and it doesn't work either

By the way, I'm using Firefox 124.0.2 (64-bit) on pc and Firefox 124.2.0 on Android 13

**Comment by Prospector** [comment]
Yeah, I found the issue. I opened a PR for fixing it here https://github.com/modrinth/knossos/pull/1673

**Comment by Aeldit** [comment]
Thanks 👌
