### ISSUE TITLE
Adblock Blocker for Individual Mod Pages

### ISSUE THREAD

**Issue by sylv256** [modrinth/knossos#1737]
### Is your suggested enhancement related to a problem? Please describe.

In lieu of [uBlock's recent decisions](https://github.com/uBlockOrigin/uAssets/pull/24161), it has become apparent that mitigations are necessary to keep revenue intact for creators.

### Describe the solution you'd like

This is why I propose a setting that allows a mod author to enable an adblock blocker on their page.

### Describe alternatives you've considered

Alternatively, we could have a dismissable prompt that asks the user to "pretty please" disable their adblock. This would be less intrusive and less "anti-user."
To quote @gorhill,
> Instead of asking a content blocker to not block certain content its meant to block, just politely ask the visitors of your website to disable their blocker, these visitors are the ones who made the decision to install a content blocker, they are the one who will decide whether they agree with your request to disable their blocker and make an exception on your website.

### Additional context

There are [currently workarounds](https://gist.github.com/sylv256/428f525c3a45f46d77c9b422c68d4e23), but those may be blocked soon as well.

**Comment by brawaru** [comment]
I don't think Modrinth can afford to play cat and mouse game with ad blockers. Moreover, anti-adblocking is anti-user and can set a bad tone (‘modrinth shoving ads down someone's throat’). Telling users why they can trust Modrinth to disable an adblocker would be nice, and we even have a support article for that,

> Alternatively, we could have a dismissable prompt that asks the user to "pretty please" disable their adblock. This would be less intrusive and less "anti-user."

However, I'm not sure if @gorhill is using uBO themselves, but uBO is pretty relentless about blocking any such messaging as well (we've tried that before), so this advice is kinda pointless 🙂 

For now creators can just set up alias links to get around this filter, like you suggested.

**Comment by sylv256** [comment]
This would be too anti-user if implemented, and good luck playing cat-and-mouse with uBlock Origin.

**Comment by ave9858** [comment]
Have you tried a "soft" anti-adblock? gorhill is the creator and maintainer of uBO, so I think his suggestion is valid for default uBO users. "Soft" anti-adblock can be dismissed and won't appear on page reload, so they aren't usually addressed in the main filters but instead a secondary annoyances filter that users have to opt-in to use.
