### ISSUE TITLE
Layout suggestions for the versions list

### ISSUE THREAD

**Issue by calloatti** [modrinth/knossos#219]
**Is your feature request related to a problem? Please describe.**

Now:
![image](https://user-images.githubusercontent.com/12817862/118954967-a7d31a80-b934-11eb-8fa7-5af605a0a908.png)

**Describe the solution you'd like**

Suggested:
![image](https://user-images.githubusercontent.com/12817862/118955019-b3bedc80-b934-11eb-83b4-25cac7ebad68.png)

- The "MOD LOADER" column title is now split in 2 lines to make the column narrower
- The loader icon is centered in the column
- The numbers in the DOWNLOADS column are right aligned, column made a bit narrower, use k,m in the future to keep numbers narrow.
- The NAME column is wider, allowing for most names to be in one line.
- MINECRAFT VERSIONS versions should be one per line to improve readability (this will increase the height in some cases). Also versions should be ordered (asc or desc) chronologically.
- STATUS indicators maybe could be replaced with B,R,A in a square box and with the proper color. This would be to make the column narrower.
- The download icon maybe it would be more accessible on the right side instead of the left side
- Maybe add a "folder" icon or similar, left of the download icon, that links to the version. Right now you have to click on the name or the version text to get there, and since those texts vary from mod to mod and version to version, it makes it harder to get used to click always on the same spot.

**Comment by Mysterious-Dev** [comment]
Maybe close this issue, because the linked PR is merged ? oO

**Comment by Redblueflame** [comment]
This was only a linked issue, not a Fixes issue. Sorry for the close/reopen.

**Comment by Redblueflame** [comment]
cf.
![image](https://user-images.githubusercontent.com/24188356/121503901-c97a6b80-c9e1-11eb-9564-6fa34b5f3ddd.png)

**Comment by Mysterious-Dev** [comment]
Hmm okay.

**Comment by wafflecoffee** [comment]
The [new design](https://knossos-g9dellpil-emmaffle.vercel.app/mod/fabric-api/versions) for the version list looks similar to this!
![image](https://user-images.githubusercontent.com/60205699/154998421-9c633881-cb0a-41e1-8cab-7159734b48c6.png)
