### ISSUE TITLE
Tags 'bleed into'/overlap other things on search page

### ISSUE THREAD

**Issue by wafflecoffee** [modrinth/knossos#230]
More PRs merged = more things for me to report :yeefuckinhaw:

**Describe the bug**
![image](https://user-images.githubusercontent.com/60205699/119866074-64574e00-beea-11eb-870d-aa3e95d78d7d.jpeg)

**To Reproduce**
On mobile, on search page

**Expected behavior**
The downloads/created/etc can be moved over to the right a bit

**Comment by venashial** [comment]
I think the mod cards are too large (tall) on mobile to begin with. Ideas:
1. Shrink icon
2. Remove text from category tags
3. Make "Downloads" ... "Available For" horizontal
4. Remove icons for "Downloads" ... "Available For"

**Comment by wafflecoffee** [comment]
> Remove icons for "Downloads" ... "Available For"

I think the created/updated could be hidden here altogether as it's not really that relevant, if we're trying to save the maximum space

**Comment by venashial** [comment]
@wafflecoffee Can you check if the tags still bleed on https://knossos-venashial-ji6dwfckt-venashial.vercel.app/?

**Comment by wafflecoffee** [comment]
They look fine to me!
![image](https://user-images.githubusercontent.com/60205699/123193514-ecd9f780-d472-11eb-9504-5266afac217a.png)

**Comment by venashial** [comment]
Yay!
