### ISSUE TITLE
Remove drop-down in menu with just buttons on mobile

### ISSUE THREAD

**Issue by wafflecoffee** [modrinth/knossos#233]
**Is your feature request related to a problem? Please describe.**
Less of a feature request and more of an enhancement.
![image](https://user-images.githubusercontent.com/60205699/119868545-29a2e500-beed-11eb-9feb-40db03b91707.png)
Having to open the drop-down to access these options is a bit counterintuitive when there's all that empty space:
![image](https://user-images.githubusercontent.com/60205699/119868688-5ce57400-beed-11eb-9785-d4e0c19eab2a.png)

**Describe the solution you'd like**
The options could be moved into the menu itself on mobile instead of having to additionally click the drop-down.

**Describe alternatives you've considered**
Keeping it as-is isn't an awful idea, just not an intuitive one either.

**Comment by venashial** [comment]
Another solution (that I would prefer) could be moving "dashboard" and "mods" into the dropdown and getting rid of the fullscreen menu altogether.

**Comment by wafflecoffee** [comment]
That's still an extra unnecessary click for the user, though.

**Comment by venashial** [comment]
This is what I was trying to say:
![image](https://user-images.githubusercontent.com/44736536/119918346-1b6cbd00-bf1d-11eb-9207-3bbcef1d6cb5.png)

**Comment by wafflecoffee** [comment]
Ohhh. Interesting concept :)
