### ISSUE TITLE
Clear all notification.

### ISSUE THREAD

**Issue by Maelep** [modrinth/knossos#257]
I think a screenshot is sufficient to explain the frustation...
![image](https://user-images.githubusercontent.com/53207714/120884886-1fb46c80-c5e6-11eb-9d2b-9a88b4bc6639.png)

Add the possibility to clear all notification at once.

**Comment by Mysterious-Dev** [comment]
I will take a look when I can ;).

**Comment by Maelep** [comment]
Thank you because I don't want to manually close the 440 notifications... xD
