### ISSUE TITLE
More filter

### ISSUE THREAD

**Issue by emielderckx** [modrinth/knossos#264]
**Is your feature request related to a problem? Please describe.**
There are a lot of performance/optimization mods on the market I would be so usefull to have an easy filter to sort these.

**Describe the solution you'd like**
A filter to sort these kinds of mods

Also an easy way for mods to show what mods are incompatible or what mods are required would be nice

**Comment by Minenash** [comment]
The main part of your request (a filter, in this case a category, for optimization mods) is a dublicate of #169.

Mods can have dependencies in the api, but they currently aren't shown on the site. Having a breaks sections along side dependencies sound pretty nice, though probably should be it's own issue.

**Comment by wafflecoffee** [comment]
Optimization category has been added: https://modrinth.com/mods?f=categories%3Aoptimization
Dependencies have been added too.
If you have any suggestions for other categories, feel free to suggest in [our Discord](https://discord.gg/EUHuJHt) :)
