### ISSUE TITLE
Better support for pixel art project icons

### ISSUE THREAD

**Issue by venashial** [modrinth/knossos#289]
**Is your feature request related to a problem? Please describe.**
Projects with pixelart icons appear blurry at most resolutions and the icon caching issue further worsens this problem.

**Describe the solution you'd like**
Remove any limits on the icon size and apply nearest neighbor upscaling through CSS.

**Comment by wafflecoffee** [comment]
> and the icon caching issue further worsens this problem

I'm pretty sure that's fixed in v2 but I could be wrong

**Comment by venashial** [comment]
Yeah, I'm pretty sure it will be "fixed" as in removing caching altogether.

**Comment by Geometrically** [comment]
V2 didn’t remove CDN caching, it removed database request caching that was added in a development version of V2. All it did was make file names on the CDN SHA1 hashes so when a new image is uploaded, the CDN caches the new image instead of sending the old one

**Comment by venashial** [comment]
Thanks for the clarification, that sounds good
