### ISSUE TITLE
Clarify that Modrinth is specifically for Minecraft mods.

### ISSUE THREAD

**Issue by Jdewi12** [modrinth/knossos#319]
The home page (https://modrinth.com/) doesn't mention anywhere that it's specifically for Minecraft. 

I imagined it being a general purpose mod-hosting website like Nexus Mods, until I actually tried to browse the mods.

**Comment by MarkusG** [comment]
IMO, this is as simple as adding the word "Minecraft" to the tagline on the front page. I've done so in #321.

**Comment by wafflecoffee** [comment]
This has been done on [the latest UI](https://staging.modrinth.com).
