### ISSUE TITLE
Remove revenue section on front page and introduce a roadmap page

### ISSUE THREAD

**Issue by MarkusG** [modrinth/knossos#322]
I believe it's misleading to detail a non-existent revenue system, with only a small note at the end of the paragraph saying that there's no ETA for its implementation. However, I understand that this is a relatively new project with lots in store for the future. Perhaps we should introduce a "Roadmap" page that sets out plans and ideas for future features?

**Comment by wafflecoffee** [comment]
There already is a brief roadmap, but it's in the [Discord server](https://discord.gg/EUHuJHt). Message link is [here](https://discord.com/channels/734077874708938864/783143123651526676/881345236742336612).

**Comment by MarkusG** [comment]
Copied the roadmap from the Discord server to a new page in #323.

**Comment by wafflecoffee** [comment]
This has been done on [the latest UI](https://staging.modrinth.com).
