### ISSUE TITLE
Unable to change License

### ISSUE THREAD

**Issue by ModProg** [modrinth/knossos#375]
### Environment

Website

### Describe the bug

I wanted to set my new project (https://modrinth.com/mod/blockmeter still pending) to the MIT license, but when I select mit in the License selector and hit save, it goes back to *ARR*

**Comment by ModProg** [comment]
still prevailing after my mod was approved

**Comment by DioEgizio** [comment]
![IMG_20220304_165637](https://user-images.githubusercontent.com/83089242/156796481-0a2b7ddb-dd9c-4e63-8388-364370d1401f.jpg)
Just for letting you know

**Comment by wafflecoffee** [comment]
Seems like this is one of those things that fixes itself when you do a browser refresh. Going to close as it's highly unlikely to be fixed on the Nuxt frontend before the rewrite is released, and none of the bug reports on the Nuxt frontend will be transferring over to the rewrite,
