### ISSUE TITLE
Clicking outside the img in expanded gallery view, should close said view

### ISSUE THREAD

**Issue by Minenash** [modrinth/knossos#405]
### Is your feature request related to a problem? Please describe.

Clicking outside the img in expanded gallery view, should close said view

### Describe alternatives you've considered

Using the close button or the esc shortcut. They're nice, but it's also instinctual to click outside to get out of it. 

### Additional context

This worked when it was first implemented

**Comment by Prospector** [comment]
I still have no idea why it worked when it was first implemented...it's not a feature I either added or removed.
