### ISSUE TITLE
"Publish, download and play Minecraft mods"

### ISSUE THREAD

**Issue by woodiertexas** [modrinth/knossos#415]
### Is your feature request related to a problem? Please describe.

Instead of "Download and publish Minecraft mods", the hover text for the modrinth tab should say "Pubish, download and play Minecraft mods".

### Describe the solution you'd like

Changing the hover text to "Publish, download and play Minecraft mods".

### Additional context

![context](https://cdn.discordapp.com/attachments/734082619352023081/951601107568853022/unknown.png)

**Comment by wafflecoffee** [comment]
But you cannot play the mods on the site itself :thinking:

**Comment by woodytexas** [comment]
well, i thought "Publish, download and play Minecraft mods" sounded better than "Download and publish Minecraft mods" because mod devs publish their mods while they can download other peoples' mods and play them in Minecraft

**Comment by woodytexas** [comment]
and generally, publishing comes before downloading and playing mods if you're a mod dev

**Comment by Prospector** [comment]
I think the current wording is fine
