### ISSUE TITLE
Long categories don't show well on mobile

### ISSUE THREAD

**Issue by link-discord** [modrinth/knossos#418]
![Screenshot_20220312-073958_Brave.jpg](https://user-images.githubusercontent.com/50463727/158007304-535337f1-0261-4cdf-947b-6226d8839930.jpg)

The tags are displayed over the mod description text which is a bit annoying. Maybe move the tags at the bottom of the card so that this doesn't happen?

**Comment by wafflecoffee** [comment]
This is fixed.
![image](https://user-images.githubusercontent.com/60205699/174520767-695e6f6d-58fc-4e08-95b3-c10980963fc7.png)
