### ISSUE TITLE
Center the input elements in User Settings > General

### ISSUE THREAD

**Issue by woodiertexas** [modrinth/knossos#420]
### Is your feature request related to a problem? Please describe.

The input elements are somewhat offcentered to the text in the User Settings > General area.

### Describe the solution you'd like

Center the input elements with the text.

### Additional context

![](https://cdn.discordapp.com/attachments/734082619352023081/953087631246360596/unknown.png)

**Comment by LoganDark** [comment]
Oh my god this is a much worse version of #423, that is SO unreadable

**Comment by wafflecoffee** [comment]
This is fixed.
![image](https://user-images.githubusercontent.com/60205699/174520843-64d7a886-32db-4a52-9585-9f47799a6df3.png)
