### ISSUE TITLE
Example code block is bold

### ISSUE THREAD

**Issue by LoganDark** [modrinth/knossos#422]
### Environment

Website

### Describe the bug

![image](https://user-images.githubusercontent.com/4723091/158556454-7d04a4ad-afa6-430f-816d-cf0f7731b03c.png)

### Steps To Reproduce

1. Go to the [landing page](https://modrinth.com/)

### Expected behavior

The code block shouldn't be bold, it looks much better at a regular weight:

![image](https://user-images.githubusercontent.com/4723091/158558723-90a04eb1-0320-4c0b-bfea-341ef4e865a9.png)

### Additional context

The font weight is inherited from `body` which specifies:

```css
font-weight: var(--font-weight-medium);
```

This should probably be overridden for code blocks.

**Comment by ubionexd** [comment]
I think it has been fixed since. For me, the code block is normal.

**Comment by LoganDark** [comment]
> I think it has been fixed since. For me, the code block is normal.

The code block is still bold on https://modrinth.com.

**Comment by wafflecoffee** [comment]
We discussed this in the Discord a bit back and came to the conclusion that it doesn't appear as bold for anyone else.  ¯\\\_(ツ)_/¯

It probably has to do with some funky system-wide font settings, if I had to guess.

**Comment by LoganDark** [comment]
> We discussed this in the Discord a bit back and came to the conclusion that it doesn't appear as bold for anyone else. ¯\_(ツ)_/¯
> 
> It probably has to do with some funky system-wide font settings, if I had to guess.

It isn't funky. Here's exactly what's happening.

1. The code block's font weight is set to 500.
2. The code block uses the browser's default monospace font.
3. Most users on Windows don't change the default monospace font from Courier New, which doesn't have a Medium weight.
4. My default monospace font is set to Input Mono which has a Medium weight.
5. The code block displays as Medium for me.
