### ISSUE TITLE
Avatar border is square even though the avatar itself is rounded

### ISSUE THREAD

**Issue by LoganDark** [modrinth/knossos#433]
### Environment

Website

### Describe the bug

The avatar border in the top right is square:

![image](https://user-images.githubusercontent.com/4723091/159410098-83f6a3e3-2945-45d6-bf2f-d40b0a7a7361.png)

### Steps To Reproduce

1. Go to modrinth

### Expected behavior

The border should be rounded.

### Additional context

You currently use `outline` for the border, apparently `outline` doesn't support shapes in all contexts. Since `border` changes the layout, you can instead use `box-shadow: 0 0 0 2px var(--color-raised-bg);`.

**Comment by wafflecoffee** [comment]
Is this still an issue?

**Comment by LoganDark** [comment]
I use Firefox now so I can't say if it was only a Google Chrome issue, but on Firefox for me the issue is fixed. But I can see it still uses outline so it was probably my browser switch

**Comment by wafflecoffee** [comment]
![image](https://user-images.githubusercontent.com/60205699/174528124-cdd4580e-a4cc-477e-8ea7-9254bfd62b9b.png)
It doesn't seem to occur on Chromium. If someone using Google Chrome specifically could confirm whether this is still an issue, that would be greatly appreciated -- otherwise this issue will be closed as stale.

**Comment by LoganDark** [comment]
I was using Chrome 91 when I reported the issue, but I later uninstalled Chrome because it found a moment when my firewall was down and instantly updated to 103 even though it wasn't open, which is a big fucking no from me.

**Comment by LoganDark** [comment]
Closing this as fixed in newer browsers
