### ISSUE TITLE
Sub roles for project members.

### ISSUE THREAD

**Issue by woodytexas** [modrinth/knossos#435]
### Is your feature request related to a problem? Please describe.

Currently, there's only member roles when it comes to project members.

### Describe the solution you'd like

A way to display sub roles for project members. Examples would be "Artist: Textures, Logo", "Developer: Worldgen Dev, Entity Dev", and so on. This would let people who run projects specify what member does what in their main role.

### Additional context

![](https://cdn.discordapp.com/attachments/734082619352023081/956406282154287124/unknown.png)

**Comment by Minenash** [comment]
Can't you basically do that already? iirc, roles themselves don't have any perms or anything, the team member does, and the roles is just a label. So I think you could add it yourself

**Comment by woodytexas** [comment]
> Can't you basically do that already? iirc, roles themselves don't have any perms or anything, the team member does, and the roles is just a label. So I think you could add it yourself

i meant something like...

User
Developer
Worldgen, Entities

**Comment by Minenash** [comment]
Unless the role field is limited to A-Za-z, can you not do that?

**Comment by woodytexas** [comment]
> Unless the role field is limited to A-Za-z, can you not do that?

not able to test that since i'm the only one listed on my modpack project

**Comment by wafflecoffee** [comment]
Any role name can be set by the project owner. Unlike CF, there is not a dropdown of only a few selectable roles.
