### ISSUE TITLE
Don't open External Resources links in a new tab

### ISSUE THREAD

**Issue by LoganDark** [modrinth/knossos#438]
### Is your feature request related to a problem? Please describe.

If I want something to open in a new tab, I'll middle-click it (or ctrl+click). If I click something normally I want it to open in the current tab! Right now external resources always load in a new tab, and in order to load in the current tab I have to manually drag it over the current tab in the tab strip. This is slow and obnoxious, and about as annoying as clicking it normally and then having to close the Modrinth page.

### Describe the solution you'd like

Don't open External Resources links in a new tab.

**Comment by LoganDark** [comment]
Since my post is getting thumbs-downs with no justification (please leave a comment!) let me just real quick outline why omitting `target="_blank"` is the best option here.

Without `target="_blank"`:

- Clicking it normally opens it in the current tab, super easy.
- Ctrl+clicking it or middle-clicking it opens it in a new tab, also super easy.

With `target="_blank"`:

- Clicking it normally opens it in a new tab, super easy.
- If you want to open it in the current tab, you have to click and drag it all the way up to the tab strip, on top of the Modrinth tab. Annoying.

There's a clear outlier here, please consider it.

**Comment by enderger** [comment]
Isn’t that available through the right click context menu as well? I use QuteBrowser, so I don’t know in this case (it’s keyboard driven).

**Comment by LoganDark** [comment]
> Isn’t that available through the right click context menu as well?

I... believe so? But that's still a lot slower than using the keyboard.

**Comment by wafflecoffee** [comment]
I don't believe we should be keeping the same tab for external links. What makes the most sense to me is that if the link is to the same site, keep the same tab, but otherwise if the link is to a different site, open a new tab.

**Comment by wafflecoffee** [comment]
I don't think most people use Modrinth as a GitHub search engine. :stuck_out_tongue: 
There's a reason they're kind of small and off to the side -- they're an afterthought compared to what you're really *supposed* to be looking at (the mod content). There are a good portion of people who don't actually know that middle click is a thing (not that this is necessarily Modrinth's demographic, but I digress), and opening in a new tab just makes the most sense to me.

> This honestly sounds like userscripts are going to save the day because I'm tired of Modrinth trying to decide *for me* where I want my tabs to go.

Watch your attitude, please. There's a reason this has the discussion tag and hasn't been closed yet. You can feel free to use a userscript; we're not going to restrict that.

**Comment by LoganDark** [comment]
> opening in a new tab just makes the most sense to me.

Again I'd like to stress the fact that this is a personal choice and Modrinth is actively making it more difficult for users who might want something different.

> Watch your attitude, please.

> You can feel free to use a userscript; we're not going to restrict that.

This was my attempt at getting it fixed for everyone rather than only myself, I have a habit of doing that. If you want to continue forcing all links to open in a new tab then I won't stop you. Only complain because it's inconvenient. I will make a userscript, but I would have preferred if, again, Modrinth didn't make browsing choices on behalf of its users.

I will stop replying here because we're just going around in circles, and I have made all the points I wanted to make. Additionally if my attitude is becoming a problem then I apologize.

**Comment by enderger** [comment]
Perhaps we could have it be a user setting, wouldn't be too hard and could nip this problem in the bud (JavaScript can query base tags and set the attribute dynamically).

**Comment by LoganDark** [comment]
While waiting on this issue to get fixed (or just in case it's closed without a resolution), here is a Tampermonkey userscript:

```js
// ==UserScript==
// @name         Remove target="_blank"
// @namespace    https://logandark.net
// @version      0.1
// @description  Gives back your choice on where to open tabs
// @author       LoganDark
// @match        https://modrinth.com/*
// @grant        none
// ==/UserScript==

(function() {
	'use strict';

	setInterval(() => { for (const link of document.getElementsByTagName('a')) link.removeAttribute('target') }, 0)
})();
```

**Comment by ix0rai** [comment]
Just adding another opinion!
As a user, I expect links that stay in Modrinth to open to the same tab, and external links to go to a new one. However, I do see this being configurable as a good idea. I think that the current behaviour should remain the default, and there should just be a checkbox to always stay in the same tab.

**Comment by Minenash** [comment]
I don't think there's a good answer to this problem.

Users expect the current behavior, and messing with expectation of how a web page acts, is kinda meh. And unfortunately, not everyone knows the ctrl+click/middle-click.

The problem with an options, is that yours is something so minor, that very few people care about, and even less people would think to look at a webpage settings to change such a fundamental behavior (which I think you can only see logged in, which I don't think most users are)

I'm not saying changing it it bad, I'm just saying there are definitely trade offs. And saying an option, while nice, would only help a handful of people, as the vast majority of people that might complain to themselves whichever way it was, would not know it's changeable

**Comment by PssbleTrngle** [comment]
This is a problem I also always face when creating a webpage and I tend to also implement it the way modrinth (and other pages) has, opening links to different pages in a new tab.

On the other hand, I think the portion of users that expect and require a specific link opening behavior, are also the users that know how to use middle-click in the browser

**Comment by triphora** [comment]
@LoganDark This can now be done by changing your settings.
![image](https://user-images.githubusercontent.com/60205699/202925507-8afad432-3f26-4dc6-9319-193a18476b07.png)
