### ISSUE TITLE
misaligned lines in the create versions section

### ISSUE THREAD

**Issue by woodiertexas** [modrinth/knossos#443]
### Describe the bug

Lines in "Create Versions" are misaligned.

### Steps To Reproduce

1. Go to Create a Project
2. Add a version

### Expected behavior

Lines should be aligned.

### Additional context

![](https://cdn.discordapp.com/attachments/734082619352023081/958941965930618950/unknown.png)

**Comment by wafflecoffee** [comment]
This seems to have been fixed.
![image](https://user-images.githubusercontent.com/60205699/174521240-b2944131-af46-4880-ae47-6ba691751b04.png)
