### ISSUE TITLE
Filter for content content/non-content  mods & content/non-content mod tags

### ISSUE THREAD

**Issue by woodiertexas** [modrinth/knossos#444]
### Is your feature request related to a problem? Please describe.

There's no way to filter between content mods or non-content mods.

### Describe the solution you'd like

A filter for  content/non-content mods and a way to tag our mods as "content mod" or "non-content mod".

**Comment by wafflecoffee** [comment]
The definition of a content mod is not an easy one to make, but I think that the server-side/client-side distinction makes this fairly easy to filter for -- personally, anyway, I believe that a content mod is one that is required on both the server and client, and that is a query that can be done in the current search: https://modrinth.com/mods?e=server,client
