### ISSUE TITLE
Cannot upload Forge mod 

### ISSUE THREAD

**Issue by tasgon** [modrinth/knossos#451]
### Describe the bug

I cannot upload the Forge version of my mod [found here](https://www.curseforge.com/minecraft/mc-mods/observable/files/3745494) to Modrinth. Attempting to create a version with it fails with no error message. No issues with the Fabric version, however.

### Steps To Reproduce

1. Click the 'Upload' button on [my mod's version page](https://modrinth.com/mod/observable/versions).
2. Fill in all details for the Forge mod.
3. Attach the mod.
4. Click save.

### Expected behavior

The mod successfully uploads, just as the Fabric version does.

**Comment by Prospector** [comment]
I imagine this is probably because you were trying to give it the same version number as an existing version? Version numbers must be unique, so you can postfix them with `+forge` and `+fabric` or something. Let me know if that was the issue!

**Comment by wafflecoffee** [comment]
No response in four weeks, closing as stale. If you still encounter this issue feel free to open a new issue.
