### ISSUE TITLE
Multilingual display mode support

### ISSUE THREAD

**Issue by PIPILAN** [modrinth/knossos#501]
### Is your feature request related to a problem? Please describe.

In the face of many different languages, only English is not conducive to development

### Describe the solution you'd like

Adding a multilingual mode like steam community allows authors to choose basic language descriptions and other languages, add language switching for the page, and switch to the introduction page of other languages that the author has made.

**Comment by Madis0** [comment]
That issue should be for the backend, which I've made here: https://github.com/modrinth/labrinth/issues/359
Frontend localization is coming soon, contribute at https://crowdin.com/project/modrinth

**Comment by wafflecoffee** [comment]
Frontend translations are coming in #345. Per-project translations is being tracked as modrinth/labrinth#359.
