### ISSUE TITLE
File size display

### ISSUE THREAD

**Issue by Madis0** [modrinth/knossos#502]
### Is your feature request related to a problem? Please describe.

I want to know how big the mod/modpack is before I download it, so I know whether there are leaner alternatives, how long the download will take, can I even download it right now etc

### Describe the solution you'd like

A file size field in the file page

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by ubionexd** [comment]
I think to solve this issue some backend changes may be required.
Packs already store file sizes, but the backend does not forward these values with knossos.

**Comment by wafflecoffee** [comment]
Added in #531 - hover over any Download button.

**Comment by Madis0** [comment]
Why hover? That's not very accessible on touch screens or on a quick glance overall.

**Comment by wafflecoffee** [comment]
Lucky for you, it's also available just off to the side of the download button on the version page.
![image](https://user-images.githubusercontent.com/60205699/174523193-42dd111a-dada-4fe9-a3b6-4e738f0f30d7.png)

**Comment by Madis0** [comment]
That is much better.
