### ISSUE TITLE
Nuxt v3

### ISSUE THREAD

**Issue by RedstoneWizard08** [modrinth/knossos#506]
### Is your feature request related to a problem? Please describe.

When I am working on features for Modrinth (for issues/PRs), it is very slow because the compiler is slow.

### Describe the solution you'd like

I would like Modrinth to update Nuxt.js to v3 in order to allow for faster and more productive development.

### Describe alternatives you've considered

N/A

**Comment by wafflecoffee** [comment]
We are switching away from Nuxt entirely in the `sveltekit-rewrite` branch, so this will resolve itself quite soon

**Comment by venashial** [comment]
(The dev server in SvelteKit is much faster than Nuxt 2's)
