### ISSUE TITLE
Gallery images upload despite getting an error

### ISSUE THREAD

**Issue by woodiertexas** [modrinth/knossos#519]
### Environment

Website

### Describe the bug

If you forget to upload an image to your project's gallery page. Any unsaved uploads will upload and the upload that has no image doesn't upload. When you update that upload to have an image and hit "Save", you'll end up uploading the same images again.

### Steps To Reproduce

1. Go to your project's gallery page.
2. Add a gallery entry with an image.
3. Add another gallery entry without an image.
4. Hit "Save".
5. Get an error about one of your gallery entries not having an image.
6. Update the image-less gallery entry to have an image.
7. Hit "Save" again.
8. You end up with duplicate gallery entries.

### Expected behavior

In the event that you forget to add an image to a gallery entry, none of the unsaved gallery entries should upload until all unsaved entries have an image.

**Comment by woodiertexas** [comment]
Extra Context: 
![image](https://user-images.githubusercontent.com/17211100/171090025-fc7365bd-c29c-43fc-979f-3d3a82deb44d.png)
https://modrinth.com/mod/arch-ex/gallery

**Comment by wafflecoffee** [comment]
I think the best solution here would probably just to be only allowing one gallery image to be saved at a time, imo.

**Comment by triphora** [comment]
Fixed in #826
