### ISSUE TITLE
Assume version name is the version itself

### ISSUE THREAD

**Issue by Madis0** [modrinth/knossos#535]
### Is your feature request related to a problem? Please describe.

I name my versions the same as the version itself. I don't want to type that twice...

### Describe the solution you'd like

- Allow me to type only the version name, assume that the version is identical
- Allow me to type only the version, assume that the version name is identical

### Describe alternatives you've considered

A button to copy value from the version?

**Comment by Prospector** [comment]
This is already how it works. If you don't supply a version name, it will use the version number as the name.

**Comment by Madis0** [comment]
I confirmed that that is not how it works right now.
When entering only the title, I get this
![image](https://user-images.githubusercontent.com/8611110/173893388-a643fa1c-3003-4ab9-96de-e15e90b0411c.png)
And when entering only the version, I get the same, except the field is "version_name".

**Comment by wafflecoffee** [comment]
This is implemented for initial version creation but not for any further version creation after that.

**Comment by wafflecoffee** [comment]
This was fixed in #616, in case GitHub's spam didn't already tell you.
