### ISSUE TITLE
Mod Language Choose

### ISSUE THREAD

**Issue by Xiaohuang257** [modrinth/knossos#557]
### Is your feature request related to a problem? Please describe.

Add a mod language choose.

### Additional context

![image](https://user-images.githubusercontent.com/81309333/176250273-2cf9a91d-1ccc-4fc6-a57a-05778078f661.png)

**Comment by wafflecoffee** [comment]
你好!
谢谢你的建议。这是我们正在计划做的事情。在 modrinth/labrinth#359 已经有一个问题。前台本身也将很快有一个翻译，这将在 modrinth/knossos#345 被合并后完成。你可以在 https://rewrite.modrinth.com 上看到一个预览。

Duplicate of modrinth/labrinth#359
