### ISSUE TITLE
Some text is obscured by the background on the main page

### ISSUE THREAD

**Issue by Gamebuster19901** [modrinth/knossos#57]
Display size: 3840x2160 (4K)

![image](https://user-images.githubusercontent.com/7155747/102293409-0d9a2100-3f15-11eb-8eb8-5ed4f552f87a.png)

**Comment by falseresync** [comment]
This might be a rendering issue on your end. May you try to edit CSS in F12 to see if this goes away?

**Comment by Gamebuster19901** [comment]
I don't believe it's a rendering issue on my end. I have to set the z-index of the hero column to 1 to get the column to render above the slanted hero.

I had to do the same with the footer too.

I'm not really a CSS guy so I couldn't figure out how to edit the .vue file for the footer (I was only able to change the z-index via F12 for the footer), but I was able to figure out what to edit for the hero column: https://github.com/Gamebuster19901/knossos/commit/841f88b895452e84730d53f8b34a56ca9be31c15

**Comment by falseresync** [comment]
Thanks for checking, no need to edit Vue, F12 is plenty enough. I believe I know how to fix this issue, you can wait a fix sometime soon-ish

**Comment by Geometrically** [comment]
@falseresync Do you know the fix

**Comment by wafflecoffee** [comment]
This was fixed in #199.
