### ISSUE TITLE
Can the site support other languages?

### ISSUE THREAD

**Issue by HexYoF** [modrinth/knossos#587]
### Is your feature request related to a problem? Please describe.

My English is not good and I encounter some obstacles when using it

### Describe the solution you'd like

Add a button to switch the language in the settings.

**Comment by Prospector** [comment]
Good news, we're working on this feature on the rewrite we're working on. You can check out the work-in-progress page here: https://rewrite.modrinth.com/ and you can change the language at the bottom of the page.

**Comment by venashial** [comment]
If the language you prefer isn't listed on https://crowdin.com/project/modrinth, let us know and we can add it.

**Comment by MMK21Hub** [comment]
If anyone has found this issue via searching, the rewrite has been cancelled. However, localisation is coming to Knossos: #738
