### ISSUE TITLE
License URL reverts back to default when editing project

### ISSUE THREAD

**Issue by LostLuma** [modrinth/knossos#597]
### Environment

Website

### Describe the bug

When going to the project edit page the license URL always reverts back to the default one on the modrinth CDN, rather than keeping the custom URL set on previous visits to the site.

### Steps To Reproduce

- Set and save a custom license URL for a project
- Re-open the project edit page and scroll down to see the default value appear again
  - Upon saving this will change the URL used on the mod page, which is unwanted

### Expected behavior

The link to my license should be kept.

### Additional context

This might be related to #593, however it also happens without changing the license that is used.

**Comment by Andre601** [comment]
I agree that this is indeed an unwanted behaviour (At least for me).
When I select `MIT` and then replace the cnd.modrinth.com URL with one to the License copy I myself have on GitHub, is it clear that I want to offer mine and not the placeholder one.

So if doable should Modrinth simply respect the URL you defined, no matter if you selected a specific license or `CUSTOM`

**Comment by LostLuma** [comment]
Hello, this issue was unfortunately not fixed with the PR it was closed from.

**Comment by Geometrically** [comment]
This PR has not been pushed to production, so it's not on the main site yet
