### ISSUE TITLE
Endless scroller for discovering mods

### ISSUE THREAD

**Issue by lucsoft** [modrinth/knossos#63]
I would love to have the option for an endless scroller

i would make a pr my self but currently i don't have much time to add it my self

**Comment by wafflecoffee** [comment]
I don't think this is very feasible for us to do. It is very bad for performance and accessibility, and doesn't work awfully well with our current API setup. It even breaks stuff like the footer and scrollbar length, which we want to keep accessible. I recommend taking a look at [this writeup](https://www.nngroup.com/articles/infinite-scrolling/) on the topic.

**Comment by lucsoft** [comment]
>  It is very bad for performance 

If we are talking about database level. I don't think it's an issue as the current way is also already inefficient

>  It even breaks stuff like the footer

Fair 😄 but back then there wasn't even a footer 

> I recommend taking a look at [this writeup](https://www.nngroup.com/articles/infinite-scrolling/) on the topic.

This concept was already implemented by the Twitch app back then, and I really liked to discover mods on that launcher 😅 and seeing all the recommended mods with no extra clicks. Like you didn't have to wait for animations and user facing loading times.

**Comment by wafflecoffee** [comment]
> If we are talking about database level. I don't think it's an issue as the current way is also already inefficient

No, in terms of stuff like the DOM getting so large that the page actually becomes sluggish to use. I guess we can keep this open for more input.

**Comment by PssbleTrngle** [comment]
> No, in terms of stuff like the DOM getting so large that the page actually becomes sluggish to use. I guess we can keep this open for more input.


There definitely would have to be some sort of virtualization that reuses DOM-Elements under to hood. I don't think this would be the part which makes the feature problematic, there are solutions for infinite scrolling virtualization

**Comment by triphora** [comment]
Sorry, but this just isn't going to happen. The new homepage thing is the closest thing that will be added, and even that is not infinite (it only updates on refresh).
