### ISSUE TITLE
Add a warning for projects licensed under proprietary licenses

### ISSUE THREAD

**Issue by MithicSpirit** [modrinth/knossos#644]
### Is your feature request related to a problem? Please describe.

Currently, the only way to determine what license a project is under is by scrolling all the way down on the page (if it is an uncommon license, it is also necessary to read/look up the license to see its details). Since I prefer to not use proprietary mods, I would like to quickly be able to tell whether it's worth my time to consider a mod or not.

### Describe the solution you'd like

The ideal solution for me would be one where the license is displayed along with the tags and available platforms (fabric, quilt, etc). The license would have a different appearance (e.g. yellow or red text) if it is proprietary.

### Describe alternatives you've considered

The above solution would probably be too intrusive for most users (as they probably do not care about proprietary software), so I think a better solution is probably one of the following:
- Same as above solution, but without the different appearance for proprietary licenses.
- A setting (similar to dark mode, but not as prominently visible) to enable proprietary license warning. The warning could be made much more overt since anyone who enables this wants to be aware of the warning. With this, I think that the best option would be to have the same solution as before but also a banner on the top of the mod page warning about the license.

**Comment by DioEgizio** [comment]
the best solution imo would be showing the license SPDX when searching, so that you also know *which* license it uses

**Comment by wafflecoffee** [comment]
Wouldn't this be accomplished by only selecting FOSS licenses in search? It could be a user setting to remove ARR and Custom from the search by default.

**Comment by MithicSpirit** [comment]
That's a half-fix. Maybe adding an exclusionary option (so it's easier than clicking most of the licenses there) would be good. Also, it doesn't solve the issue of having to scroll all the way down (which on some mods that support a myriad of versions can be quite long) to find out the license when already on the mod page.

**Comment by wafflecoffee** [comment]
We were already planning on making it a single checkbox for "Exclude proprietary licenses" rather than the full dropdown that we have there. I'm not sure whether it's important to emphasize whether a mod is proprietary on the mod page itself, as long as it's possible to have that in search.

**Comment by MithicSpirit** [comment]
Being able to quickly see the license or whether it's FOSS/proprietary would still be convenient for when I'm sent links, but it's a minor improvement for me and completely useless for the vast majority of other users, so it makes sense if the license information is kept relegated to the bottom of the sidebar.
The "Exclude proprietary licenses" checkbox in search sounds like a good idea though.

**Comment by Prospector** [comment]
Closing this as a duplicate since implementing the Visible source and Open source badges as discussed in #196 would solve this issue.
