### ISSUE TITLE
Version filter for notifications and other small ideas

### ISSUE THREAD

**Issue by mrniddala** [modrinth/knossos#692]
### Describe the solution you'd like

Hello 🥰

I would love to have a **master option** for each category (mods, plugins, resourcepacks - modpacks has no use I think?) to receive only notifications for a specific Minecraft version.
Some authors publishing updates for 6+ versions at once and it fills the notification area up.

Further - you could add the ability to chose individual for each category the version you wan't to receive notifications for (and a check if it should ignore the **master option**).

Splitting the "Followed Projects" category into respective single categories. But it can still exist as list for all at once.

Adding a search bar. Yes, you could simple search inside of your browser but Modrinth comes up with a smooth searching. 
Let it shine on the "Followed Projects" tab too.

EDIT: A direct download button in the Notifications area next to the **Dismiss** button would be nicee too.

That's all my ideas for now - I see the notification thing as really important.

**Comment by Minenash** [comment]
Not exactly what you requested, but this PR should reduce the spam of a project releasing multiple versions at once: #671

**Comment by wafflecoffee** [comment]
Just because something hasn't gotten attention doesn't mean that it's not planned or anything. Right now development focus is largely on the roadmap items, and these are things that can be PRed by anyone.

**Comment by MopsTMC** [comment]
I did not, in any way, mean to sound impulsive and I'm sorry if I did. I understand that this isn't of priority currently. I just wanted to share some additional ideas on the topic with anyone who could've come across this feature request.

**Comment by triphora** [comment]
> I would love to have a master option for each category (mods, plugins, resourcepacks - modpacks has no use I think?) to receive only notifications for a specific Minecraft version.
> Some authors publishing updates for 6+ versions at once and it fills the notification area up.
> Further - you could add the ability to chose individual for each category the version you wan't to receive notifications for (and a check if it should ignore the master option).

This is a case of the XY problem, the real solution here should come in the form of something like #671.

> Splitting the "Followed Projects" category into respective single categories. But it can still exist as list for all at once.

modrinth/.github#28

> Adding a search bar. Yes, you could simple search inside of your browser but Modrinth comes up with a smooth searching.

Modrinth has a search bar for each project type and Opensearch integration, not sure if there's anything else you would want

> EDIT: A direct download button in the Notifications area next to the Dismiss button would be nicee too.

Please make a separate issue for this. In the future, do not create conglomerate issues like this; please create a separate issue for each separate item you wish to address.
