### ISSUE TITLE
Clicking 'Submit for review' displays endless progress bar

### ISSUE THREAD

**Issue by ejm554** [modrinth/knossos#711]
### Environment

Website

## Description

After filling out a 'Create a project' form and clicking the 'Submit for review' button, a progress bar appears on the upper-left part of the screen. It seems to start & restart in an endless loop. Nothing else appears on my screen. It seems that my project is never submitted. The same behavior occurs if I click on 'Save as draft,' and a draft is never saved.

## Animation showing issue
![Screenshot 2022-10-30-A](https://user-images.githubusercontent.com/26723535/199261902-1baf5a69-3bb3-4b20-8dab-83721f6363fd.gif)

### Steps To Reproduce

1. Go to the 'Create a project' page.
2. Fill out the required parts of the form.
3. Click 'Submit for review' or 'Save as draft.'

### Expected behavior

I'd expect to see one or more of the following:
1. A progress bar that advances to a point of completion.
2. Perhaps some text stating explicitly what step is occurring in the submission process.
3. An error message if there is a problem with the data or file(s) that I'm trying to submit.
4. A 'success' message.
5. A saved draft of my project.

### Additional context

Device details
Computer OS: Windows 10
Browser: Firefox 106.0.2

**Comment by triphora** [comment]
This always occurs with large modpacks, and will submit eventually. It's not necessarily a bug, despite how glitchy it is; it's just slower the larger the files that need to be uploaded. There is not really any way to have an accurate loading bar here, so Nuxt does its best.

**Comment by ejm554** [comment]
Good to know. Still, it would be nice if something else could communicate that uploading is occurring. Maybe just a message letting users know that something is happening, or that it's normal for bigger modpacks to take a while?

Ideally, something showing me the details, like _x_ MB out of _y_ MB have been transferred, but I presume that may be too complicated to do in the short run.

**Comment by triphora** [comment]
Eventually the "create project" page will not exist at all as of #647. By forcing users to upload files on the version page, I think it will make it clear that the reason it's taking so long is because it's uploading said files. We are yet to see, though.
