### ISSUE TITLE
Project not found error although project does exist

### ISSUE THREAD

**Issue by baraclese** [modrinth/knossos#717]
### Environment

Website

### Describe the bug

I get a project not found error when searching for the GlobalSpawn mod.

### Steps To Reproduce

- go to https://modrinth.com/mods?q=globalspawn&s=newest
- click on GlobalSpawn Mod
- receive 'project not found' error

### Expected behavior

Expect to see the project site https://modrinth.com/mod/globalspawn

**Comment by jadelily18** [comment]
incredibly weird bug
![CORS errors](https://user-images.githubusercontent.com/74706690/201132024-fd62d090-21a2-4ea7-b161-2009608b280f.png)

**Comment by triphora** [comment]
...oh wow, I didn't think there were any projects left that still used the old way of adding descriptions

Will fix momentarily

**Comment by triphora** [comment]
Fixed for this specific mod and will be fixing soon for any other mods which use this method. Thanks for the report!
