### ISSUE TITLE
Support .sk files (Skript Plugins)

### ISSUE THREAD

**Issue by YM2IT** [modrinth/knossos#733]
### Is your feature request related to a problem? Please describe.

I think It'd be a good idea to add support to .sk files which are Skript plugins

**Comment by SylvKT** [comment]
> **Skript** is (surprise, surprise) a scripting plugin for the Bukkit platform. It is easy to use for simple tasks, but you can also create really complex things with it. The syntax of Skript is close to English, but it is still not magic. While you might succeed with experimentation for simple tasks, for anything more complex you will need some guidance.

<sub>[source](https://docs.skriptlang.org/)</sub>

Why should this be supported? This is for a specific Bukkit plugin, not a mod loader or server software with plugins. Furthermore, I don't think this is popular enough to warrant such a thing.

**Comment by Andre601** [comment]
Skript is a joke in the plugin community to be honest.

Me and many other devs don't consider it actual programming and more text editing.
I feel like allowing skripts here would only lower the quality of the shared resources, especially since so many try to make a all-in-one skript, which isn't what skript is useful for.

**Comment by Patbox** [comment]
As someone who did scripts using it before picking up actual modding I can't agree with it being a joke/not programming. It is by all definition actual programming launguage, even if it isn't standalone (which other games did in the past). In right hands it can be rather powerful, even comparable with regular plugins ability wise (with right addons/good coder and ignoring it being slower than jvm code). But yeah I can agree that modrinth isn't good place for them, as many public ones aren't too great quality wise (and there are other places for them)
