### ISSUE TITLE
URL (Slug) setting has missplaced text

### ISSUE THREAD

**Issue by Andre601** [modrinth/knossos#744]
### Environment

Website

### Describe the bug

When editing your project is the slug/URL setting displaying the slug with a completely different vertical position than the URL itself.

Example:
![example](https://cdn.discordapp.com/attachments/734077874708938867/1042759348918698065/image.png)

### Steps To Reproduce

1. Edit a project
2. Notice the missaligned text in the URL field

### Expected behavior

The text should be aligned properly

### Additional context

Browser: Firefox 107.0 (64-Bit)
OS: Windows 10

**Comment by Andre601** [comment]
Also, for the sake of consistency did I check another of my resources and it's the same there.
![grafik](https://user-images.githubusercontent.com/11576465/202554606-ae39ceb5-0a14-41a2-bee5-b2d0ba3813f6.png)

**Comment by triphora** [comment]
Can you still reproduce this issue @Andre601?

**Comment by Prospector** [comment]
Pretty sure I've seen a bunch of recent messages reporting it on discord. Seems to be a Firefox exclusive issue?

**Comment by triphora** [comment]
I don't see it on Firefox on Linux, so it could be Windows-only

**Comment by Andre601** [comment]
Seems to be fine on the production site.

**Comment by Prospector** [comment]
wonder if someone fixed it or if Firefox did lol... I sure didn't fix it
