### ISSUE TITLE
Provide Option to show estimate revenue in other Currency in Dashboard

### ISSUE THREAD

**Issue by Arbee4ever** [modrinth/knossos#764]
### Is your feature request related to a problem? Please describe.

I live in Europe and use the € as my main Currency, this result in the Revenue Display on the Dashboard being effectively useless for me because I have no way of knowing how much that is in €.

### Describe the solution you'd like

Add a Selector for other Currencies to display an Estimate on what I would get in that Currency.

### Describe alternatives you've considered

Look it up on Google everytime (bad UX)

**Comment by triphora** [comment]
It is bad UX, but doing this would make us rely on an external currency API, each of which are subject to a million different caveats. Namely that no one currency converter can be 100% correct, and that they almost never line up with PayPal's conversions.
