### ISSUE TITLE
Knossos doesn't replace invalid characters when copying from the name field to the url field

### ISSUE THREAD

**Issue by jadelily18** [modrinth/knossos#785]
### Describe the bug

When creating a new project, the apostrophe from the name input is kept in the URL's input. For example, the name of `Jade's Mod` would be changed to `jade's-mod`. (Don't mind the pink user style :D)

![example of bug](https://user-images.githubusercontent.com/74706690/204683256-24fc6fda-b525-41a7-9bd5-f4e9aa292657.png)

### Steps to reproduce

1. Open the "create a project" modal from the profile dropdown or user page
2. Type a project name with an apostrophe

### Expected behavior

The apostrophe should be removed from the URL slug by default.

**Comment by triphora** [comment]
Apostrophes are allowed in slugs, though

**Comment by jadelily18** [comment]
> Apostrophes are allowed in slugs, though

but... https://discord.com/channels/734077874708938864/783153806531100673/1047291343011070046

**Comment by Minenash** [comment]
Yeah
[this](https://github.com/modrinth/labrinth/blob/ba28bc94d315c3f6ebb2c71a3daffd8d0317b949/src/util/validate.rs#L8) says `` a-zA-Z0-9!@$()`.+,_ `` with `` ` `` being a grave/backtick not an apostrophe.

(and I see that you outdated the comment, but wanted to explain for others reading)

**Comment by Minenash** [comment]
To broaden the issue's title:
Knossos doesn't replace invalid characters when copying from the name field to the url field. It only lowercases and replaces spaces with dashes.

**Comment by Geometrically** [comment]
oops I copied the regex from online, it should not allow apostrophe

**Comment by Minenash** [comment]
Unless there's a regex I missed, none contains an apostrophe in it?
