### ISSUE TITLE
Allow ZIP files for mod packs.

### ISSUE THREAD

**Issue by MIfoodie** [modrinth/knossos#803]
### Is your suggested enhancement related to a problem? Please describe.

Some malingers/launchers don’t allow your weird file format.

### Describe the solution you'd like

Allow for the uploading of .zip files for mod packs.

**Comment by triphora** [comment]
We support the [Modrinth format](https://docs.modrinth.com/docs/modpacks/format_definition/) exclusively.

**Comment by Gaming32** [comment]
mrpacks are technically zips with a different extension.
