### ISSUE TITLE
Issues with the mod settings page

### ISSUE THREAD

**Issue by magistermaks** [modrinth/knossos#82]
1. When the "reset icon" button is clicked and the setting are saved the page hangs up (it doesn't redirect the user, and settings are unsaved) and a following error is written to the JS console: `TypeError: "t.t0.response is undefined" NuxtJS`    

2. It's impossible to change the mod icon (the icon stays unchanged after saving modified settings)  

3. If the License field (which is optional) is left empty during creation of a mod, the error "`Error while parsing JSON: invalid type: null`"  is shown to the user

4. If a required field is left empty during creation of a mod, the error "`Error while parsing JSON: invalid type: null`" - this one is not strictly a bug, but a more user friendly message should be provided (e.g. "Please fill in missing required fields.")

**Comment by Geometrically** [comment]
I've tried to reproduce 1 & 2 by changing the icon, which works. However, it does not work if you try to "delete" the icon by clicking reset, and then save. I've created an issue in the backend for this: https://github.com/modrinth/labrinth/issues/137

**Comment by Geometrically** [comment]
I'm pushing a commit soon which fixes 3 & 4
