### ISSUE TITLE
Category icons are in wrong spot in epiphany

### ISSUE THREAD

**Issue by i509VCB** [modrinth/knossos#83]
Browser: `epiphany 3.38.2-1`

Screenshot:

![Screenshot_20210117_191055](https://user-images.githubusercontent.com/30619168/104862073-250c6580-592a-11eb-9d11-d9fa2e1d9dfd.png)

**Comment by Geometrically** [comment]
I think this is something to do with flexbox on WebKit based browsers (safari included)

**Comment by Geometrically** [comment]
Could you check this again? I think it might be fixed now.

**Comment by ZtereoHYPE** [comment]
Fixed for me!
