### ISSUE TITLE
"Browse" Tab cut off on Phones (IOS and Android)

### ISSUE THREAD

**Issue by zax71** [modrinth/knossos#843]
### Describe the bug

On an iPhone 7 in all browsers (I cannot reproduce this in Firefox using developer tools) the Modpacks button is cut off of the browse tab.

![Displaying bug](https://cdn.discordapp.com/attachments/783153806531100673/1061559711998160946/IMG_2769.png)

### Steps to reproduce

1. Find a real iPhone 6, 7 or 8 (Untested on 6 or 7, but they have the same screen size)
2. Go to [Modrinth](https://modrinth.com) in a browser of your choice 
3. Click on "Browse"
4. Notice the Modpacks button being cut off

### Expected behavior

I would expect the modpacks button not to be cut off

### Additional context

As stated above, this does not occur on an emulated iPhone 7 using Firefox developer tools but only on the real hardware

**Comment by BluePsychoRanger** [comment]
I can confirm it also looks like that on an iPhone 11 Pro and iPhone XS. Looks fine on an 11 inch iPad Air.

**Comment by zax71** [comment]
I've changed the title to reflect that, I can only assume it is all iPhones

**Comment by ZtereoHYPE** [comment]
<img width="1440" alt="Screenshot 2023-01-08 at 13 48 30" src="https://user-images.githubusercontent.com/57519662/211196918-8fae6ec9-bd0f-4851-8379-719035db67d6.png">
does not happen on safari for mac, neither in resposnive design mode nor in normal vertical windows

**Comment by Voxxin** [comment]
> I've changed the title to reflect that, I can only assume it is all iPhones then. It could also be a safari bug only on portrait screens though, so if someone on a Mac could test it, that would be great

I get the same issue on Chrome with an iPhone XR.

**Comment by jadelily18** [comment]
it displays normally for me on an iPhone 14 Pro Max on safari

**Comment by HyperSoop** [comment]
can reproduce on BQ-5003L (android 7.0) firefox stable 108.2.0

**Comment by Geometrically** [comment]
It looks like a browser bug caused by the text wrapping when it shouldn't. Will look into it

**Comment by Prospector** [comment]
No longer relevant with the new UI
