### ISSUE TITLE
[bug] Notifications icon is smaller than the other ones

### ISSUE THREAD

**Issue by Siphalor** [modrinth/knossos#85]
Don't know what to say more about it. Check it out yourself - probably just a wrong number somewhere:

![image](https://user-images.githubusercontent.com/24505659/105208753-57e07480-5b49-11eb-9bde-20bf11f67993.png)

**Comment by Geometrically** [comment]
![image](https://user-images.githubusercontent.com/18202329/112709429-cf4ac100-8e76-11eb-94d4-ac10bae984ca.png)
What browser, and what screen size? I can't seem to reproduce.

**Comment by Siphalor** [comment]
I can confirm this on any iOS browser I tried on my iPhone SE - So seems broken on WebKit.

I can also confirm this on Firefox 87 (currently on Linux Mint but pretty sure I did the original screenshot on Windows).

I'm using a 4k screen with 2x upscaling but I don't think that matters since the same glitch happens on WebKit.
