### ISSUE TITLE
[BUG] Mods accept invalid Supported Versions

### ISSUE THREAD

**Issue by MMK21Hub** [modrinth/knossos#86]
Mod entries (specifically mod versions), the Supported Versions can contain any MC version, even if that version is invalid (e.g. Fabric mods can't be for <1.14)

**Comment by falseresync** [comment]
This is intended, as we cannot say for sure it is unsupported. For example, there are fully compatible/compliant Fabric forks that work on 1.8.9 and on infdev

**Comment by MMK21Hub** [comment]
Hm, makes sense. I'll open a separate issue for large amounts of Supported Versions breaking the UI than.
