### ISSUE TITLE
Support Forge jarfile version substitution

### ISSUE THREAD

**Issue by necauqua** [modrinth/knossos#891]
### Is your suggested enhancement related to a problem? Please describe.

When you upload a forge mod past 1.13, the version name is loaded from the `mods.toml` file it seems.
In forge there is a feature where it substitutes a string `${file.jarVersion}` with a value from the `Implementation-Version` value in the jar manifest (`META-INF/MANIFEST.MF`).

Currently when I upload the jar the version gets set to that string and I have to fix it.

### Describe the solution you'd like

Since you're already loading the version from `META-INF/mods.toml` file, it should be easy to substitute the string `${file.jarVersion}` with the `Implementation-Version` from `META-INF/MANIFEST.MF`

**Comment by Prospector** [comment]
Would you mind linking a mod that uses this feature? Would like it for testing purposes

**Comment by necauqua** [comment]
I am in the middle of migrating one of my mods to mondrinth as I found that, so you can use [that](https://github.com/necauqua/subpocket/releases/tag/v1.18-8.0.1.1)
