### ISSUE TITLE
Filter by license?

### ISSUE THREAD

**Issue by idwtd** [modrinth/knossos#9]
Would filtering mods by license be possible?

**Comment by Geometrically** [comment]
We could look into it, at the moment, no

**Comment by Aeledfyr** [comment]
We don't currently have licensing information about mods on the backend (labrinth).  Adding that shouldn't be too difficult, but we'll have to support many different types of licenses or the lack thereof.  It will be more difficult to get the license information for curseforge mods, as I don't think that that is available through the methods that we are using.

**Comment by idwtd** [comment]
Any updates on this? (I see Modrinth now supports licensing information)

**Comment by Geometrically** [comment]
It's possible through the backend, it just has to be added to the frontend
