### ISSUE TITLE
Site never loads in iOS Safari (sometimes)

### ISSUE THREAD

**Issue by Gaming32** [modrinth/knossos#912]
### Describe the bug

Sometimes it just loads forever.

### Steps to reproduce

1. Buy an iPhone
2. Open Safari
3. Go to modrinth.com
4. Sometimes it never loads

### Expected behavior

It should always load.

**Comment by triphora** [comment]
I don't think anyone else has reported/observed this issue since this was opened.

**Comment by Gaming32** [comment]
I have personally experienced it. If I restart Safari, it works.
