### ISSUE TITLE
Moderation status card phrasing 

### ISSUE THREAD

**Issue by input-Here** [modrinth/knossos#915]
### Describe the bug

The moderation status card button says "Resubmit for review" even when a project has not yet been submitted.
![image](https://user-images.githubusercontent.com/109800890/212386047-8f0dc201-9365-403b-a75e-54157bcb174c.png)
The button could also be greyed out until the project is eligible to submit (Such as including a version)

### Steps to reproduce

1. Create a new draft
2. Check the moderation status card 

### Expected behavior

The button to initially say "Submit for review" like on the project checklist, and then "Resubmit for review" once a project has been rejected for whatever reason

**Comment by MMK21Hub** [comment]
According to [Prospector on Discord](https://canary.discord.com/channels/734077874708938864/734077874708938867/1065315913399799961), the card shouldn't be shown at all for new projects.
![image](https://user-images.githubusercontent.com/50421330/213491960-46c0eef8-52f7-4f4d-bf44-c59c2e351eb8.png)

Having said that, I can confirm this issue.

**Comment by triphora** [comment]
Yep that is addressed in #920
