### ISSUE TITLE
Gallery image publishing checklist item description is ambiguous

### ISSUE THREAD

**Issue by MMK21Hub** [modrinth/knossos#934]
### Describe the bug

The "Feature a gallery image" item on the new project publishing checklist has the following description:
> Featured gallery images may be the first impression **of** many users.

Using the word "of" suggests that the impression is of the users, but it's meant to refer to the impression of the project. It should probably say something like this:

> Featured gallery images may be the first impression <ins>for</ins> many users.

### Steps to reproduce

1. Create a new draft: https://modrinth.com/create/project
2. Go to the project page of the new draft
3. Expand the publishing checklist (if it isn't already)

**Comment by Prospector** [comment]
well, the impression is *of* the users, it's their impression. I don't think the language is wrong, but a little ambiguous perhaps.

**Comment by MMK21Hub** [comment]
I can see why "of" would make sense, although I still think that it'd be confusing, as "of" is more often used in the opposite way, e.g. "My first impression of the project".
