### ISSUE TITLE
Discord widget support

### ISSUE THREAD

**Issue by BrownTurtleBear** [modrinth/knossos#983]
### Describe the solution you'd like

Each discord server can enable widgets to post onto their own websites to advertise the server. The widget uses HTML and makes a lot of sense if the description of each pack is supported.

**Comment by Minenash** [comment]
Just to comment the available alternatives as of now:
- It's one of the link available in the "External Resources"
- You use "badge" (like devin's)
<img alt="discord-plural" height="56" src="https://cdn.jsdelivr.net/npm/@intergrav/devins-badges@3/assets/cozy/social/discord-plural_64h.png">

On the technical side, the only thing needed to add support is to add another exception to the block i-frame rule
