### ISSUE TITLE
Homepage icon border radiuses do not align

### ISSUE THREAD

**Issue by input-Here** [modrinth/knossos#990]
### Describe the bug

The corner radius of the background of the homepage icons doesn’t align with the border’s corner radius, creating a misalignment

![9DD04965-5073-403E-AA9E-E78F6BFF507B](https://user-images.githubusercontent.com/109800890/218268451-6fc3c956-a07b-42db-b78b-46c79f44a999.jpeg)

### Steps to reproduce

1. Go to homepage
2. Zoom in on the icons

### Expected behavior

That the icon and border radiuses align

**Comment by MMK21Hub** [comment]
Can confirm. For ease of convenience, here's a link to [Modrinth's landing page](https://modrinth.com/), where this issue can be reproduced.

h3. Code analysis

The outer background colour [has a border radius of `0.75rem`](https://github.com/modrinth/knossos/blob/6a52d03329ec62e86d7c5a06153119bf5790fbcc/pages/index.vue#L1091), whereas the inner border [has a border radius of `1rem`](https://github.com/modrinth/knossos/blob/6a52d03329ec62e86d7c5a06153119bf5790fbcc/pages/index.vue#L1168), and the difference between the two introduces this visual bug. To fix the issue, the border radius of `.creator-section .features .feature .icon` should be increased from `0.75rem` to `1rem` to match the grey border.

Here's a screenshot with that fix applied.
![Matching border radii](https://user-images.githubusercontent.com/50421330/218662507-dc30fec1-5cc8-4e99-a6e8-a454cb50162f.png)

**Comment by MagnusHJensen** [comment]
> Can confirm. For ease of convenience, here's a link to [Modrinth's landing page](https://modrinth.com/), where this issue can be reproduced.
> 
> h3. Code analysis
> 
> The outer background colour [has a border radius of `0.75rem`](https://github.com/modrinth/knossos/blob/6a52d03329ec62e86d7c5a06153119bf5790fbcc/pages/index.vue#L1091), whereas the inner border [has a border radius of `1rem`](https://github.com/modrinth/knossos/blob/6a52d03329ec62e86d7c5a06153119bf5790fbcc/pages/index.vue#L1168), and the difference between the two introduces this visual bug. To fix the issue, the border radius of `.creator-section .features .feature .icon` should be increased from `0.75rem` to `1rem` to match the grey border.
> 
> Here's a screenshot with that fix applied. ![Matching border radii](https://user-images.githubusercontent.com/50421330/218662685-37f6fe98-e301-45e2-a13e-405b3d6ba1d5.png)

Lets see that PR! 🥳

**Comment by triphora** [comment]
Fixed in #1027
