### ISSUE TITLE
When using modrinth on second monitor mobile mode gets triggered

### ISSUE THREAD

**Issue by xlifi** [modrinth/knossos#995]
### Describe the bug

When browser is opened on my second screen website displays mobile version

### Steps to reproduce

Open browser from your computer
Go on modrinth.com
Shrink browser width to 1080px

### Expected behavior

Website displays desktop version

### Additional context

My second monitor is rotated 90 degrees so it's aspect ratio is 9:16. Firefox is taking half of the screen (1080x960 Width x Height). Issue first appeared since last redesign

**Comment by HyperSoop** [comment]
It's probably in "tablet mode", and i don't think it's a bug, just an annoyance in this specifc case. Could be fixed just by adjusting some things i think, but I'm not sure if that can be done without sacrificing usability for actual tablet users.

**Comment by xlifi** [comment]
> It's probably in "tablet mode", and i don't think it's a bug, just an annoyance in this specifc case. Could be fixed just by adjusting some things i think, but I'm not sure if that can be done without sacrificing usability for actual tablet users.

There are a lot of styles for min-width 1100, 1095 and 1024. Why not use 1024 for all styles?

**Comment by OrdinaryCloverOC** [comment]
mtp:/Pixel 6/Internal shared storage/Pictures/Screenshots/Screenshot_20230220-125301.png steam deck issue as well. possibly related. 16:10 aspect ratio (10:16 on it's side technically) steam deck has weird resolution workarounds.

**Comment by xlifi** [comment]
stale, fixed by using website at 90% scale. closing
